import type { TrDict } from "./types";

/** Factory Brain module views. */
export const brainDict: TrDict = {
  // —— sub-nav tab labels ——
  "Executive Summary": { th: "สรุปสำหรับผู้บริหาร", ja: "エグゼクティブサマリー", zh: "高管摘要" },
  "Factory Health": { th: "สุขภาพโรงงาน", ja: "工場ヘルス", zh: "工厂健康度" },
  "Critical Issues": { th: "ปัญหาวิกฤต", ja: "重大な問題", zh: "关键问题" },
  "Opportunities": { th: "โอกาส", ja: "機会", zh: "机会" },
  "AI Copilot": { th: "ผู้ช่วย AI", ja: "AIコパイロット", zh: "AI副驾" },

  // —— executive briefing · KPI band ——
  "Overall OEE": { th: "OEE รวม", ja: "総合OEE", zh: "综合OEE" },
  "Energy · Today": { th: "พลังงาน · วันนี้", ja: "エネルギー · 本日", zh: "能耗 · 今日" },
  "Cost / Unit": { th: "ต้นทุน / หน่วย", ja: "単位コスト", zh: "单位成本" },
  "Carbon": { th: "คาร์บอน", ja: "カーボン", zh: "碳排放" },
  "Open Risks": { th: "ความเสี่ยงที่เปิดอยู่", ja: "未対応リスク", zh: "未处理风险" },

  // —— executive briefing · letterhead / health card ——
  "Live": { th: "ขณะนี้", ja: "ライブ", zh: "实时" },
  "Good": { th: "ดี", ja: "良好", zh: "良好" },
  "vs. last week": { th: "เทียบสัปดาห์ก่อน", ja: "先週比", zh: "较上周" },

  // —— executive briefing · section headings ——
  "Financial Impact": { th: "ผลกระทบทางการเงิน", ja: "財務影響", zh: "财务影响" },
  "Recommended Actions": { th: "การดำเนินการที่แนะนำ", ja: "推奨アクション", zh: "建议措施" },

  // —— executive briefing · footer / buttons ——
  "Generated by": { th: "สร้างโดย", ja: "生成:", zh: "生成方" },
  "Confidential": { th: "ความลับ", ja: "社外秘", zh: "机密" },
  "Print": { th: "พิมพ์", ja: "印刷", zh: "打印" },
};
