import type { TrDict } from "./types";

/** Energy module views (Overview / Live / Peak & Cost / Savings / AI Optimization).
 *  Power Quality strings live in lib/autotranslate.ts. */
export const energyDict: TrDict = {
  /* ---------------------------------------------------------------- Overview */
  "Energy is running": { th: "การใช้พลังงานอยู่ที่", ja: "エネルギー使用量は", zh: "能耗运行在" },
  "above the 30-day baseline": {
    th: "สูงกว่าค่าฐาน 30 วัน",
    ja: "30日間のベースラインを上回っています",
    zh: "高于30天基线",
  },
  "Main driver: Chiller B drawing +23 kW from condenser fouling (฿4,500/wk). Dispatching the condenser clean recovers most of today's drift.":
    {
      th: "ปัจจัยหลัก: Chiller B ดึงกำลังไฟเพิ่ม +23 kW จากคอนเดนเซอร์อุดตัน (฿4,500/สัปดาห์) การสั่งล้างคอนเดนเซอร์จะช่ว·ู้คืนส่วนเบี่ยงเบนของวันนี้ได้เกือบทั้งหมด",
      ja: "主要因: コンデンサーの汚れによりチラーBが+23 kW多く消費しています (฿4,500/週)。コンデンサー洗浄を実施すれば本日のドリフトの大半を回復できます。",
      zh: "主要原因：冷凝器结垢导致冷水机组B多耗+23 kW（฿4,500/周）。安排清洗冷凝器可回收今日大部分偏移量。",
    },
  "Ask why": { th: "ถามเหตุผล", ja: "理由を尋ねる", zh: "询问原因" },
  "Fix it": { th: "แก้ไข", ja: "対処する", zh: "立即修复" },
  "Peak demand hit": { th: "ความต้องการสูงสุดแตะ", ja: "最大需要が到達", zh: "峰值需求达到" },
  "kW over the": { th: "kW เกินกว่า", ja: "kW超過", zh: "kW超出" },
  "kW contract": { th: "kW ตามสัญญา", ja: "kW契約値", zh: "kW合约值" },
  "of contract": { th: "ของสัญญา", ja: "契約比", zh: "合约占比" },
  "est. penalty": { th: "ค่าปรับโดยประมาณ", ja: "推定ペナルティ", zh: "预计罚款" },
  "Prevent next peak": { th: "ป้องกันพีคครั้งถัดไป", ja: "次のピークを防止", zh: "预防下次峰值" },
  "Energy Health Score": { th: "คะแนนสุขภาพพลังงาน", ja: "エネルギー健全性スコア", zh: "能源健康评分" },
  Healthy: { th: "ปกติ", ja: "良好", zh: "健康" },
  "load factor": { th: "แฟกเตอร์โหลด", ja: "負荷率", zh: "负载率" },
  "Budget pacing · this month": {
    th: "การใช้จ่ายตามงบ · เดือนนี้",
    ja: "予算ペース · 今月",
    zh: "预算进度 · 本月",
  },
  "Spend · MTD": { th: "ค่าใช้จ่าย · ตั้งแต่ต้นเดือน", ja: "支出 · 月初来", zh: "支出 · 本月至今" },
  Budget: { th: "งบประมาณ", ja: "予算", zh: "预算" },
  "Forecast · month-end": { th: "คาดการณ์ · สิ้นเดือน", ja: "予測 · 月末", zh: "预测 · 月末" },
  "Forecast exceeds budget — PeakShield can recover ~฿180K this month.": {
    th: "คาดการณ์เกินงบ — PeakShield สามารถประหยัดได้ราว ฿180K ในเดือนนี้",
    ja: "予測が予算を超過 — PeakShieldで今月約฿180Kを回収可能です。",
    zh: "预测超出预算 — PeakShield 本月可回收约 ฿180K。",
  },
  "Time-of-Use · MTD": { th: "อัตราตามช่วงเวลา · ตั้งแต่ต้นเดือน", ja: "時間帯別料金 · 月初来", zh: "分时电价 · 本月至今" },
  "On-Peak Energy": { th: "พลังงานช่วงพีค", ja: "オンピーク電力量", zh: "峰时电量" },
  "Off-Peak Energy": { th: "พลังงานช่วงออฟพีค", ja: "オフピーク電力量", zh: "谷时电量" },
  "Peak Demand · MTD": { th: "ความต้องการสูงสุด · ตั้งแต่ต้นเดือน", ja: "最大需要 · 月初来", zh: "峰值需求 · 本月至今" },
  penalty: { th: "ค่าปรับ", ja: "ペナルティ", zh: "罚款" },
  occurred: { th: "เกิดขึ้นเมื่อ", ja: "発生", zh: "发生于" },
  "Typical Peak Hours": { th: "ช่วงเวลาพีคทั่วไป", ja: "典型的なピーク時間帯", zh: "典型峰值时段" },
  "of daily peaks this month": {
    th: "ของพีครายวันในเดือนนี้",
    ja: "が今月の日次ピークを占めています",
    zh: "占本月日峰值",
  },
  "Consumption by Weekday": { th: "การใช้พลังงานตามวันในสัปดาห์", ja: "曜日別消費量", zh: "按工作日消耗" },
  Wednesday: { th: "วันพุธ", ja: "水曜日", zh: "星期三" },
  "runs highest — avg": { th: "ใช้สูงสุด — เฉลี่ย", ja: "が最も高い — 平均", zh: "最高 — 平均" },
  "Top consumers · now": { th: "อุปกรณ์ใช้พลังงานสูงสุด · ตอนนี้", ja: "消費量上位 · 現在", zh: "耗能大户 · 当前" },
  live: { th: "เรียลไทม์", ja: "ライブ", zh: "实时" },
  "Top 5 share of plant load": {
    th: "สัดส่วนโหลดโรงงานของ 5 อันดับแรก",
    ja: "上位5件の工場負荷比率",
    zh: "前5名占厂区负载比例",
  },
  "vs 7-day avg — condenser fouling": {
    th: "เทียบค่าเฉลี่ย 7 วัน — คอนเดนเซอร์อุดตัน",
    ja: "7日間平均比 — コンデンサー汚れ",
    zh: "对比7天均值 — 冷凝器结垢",
  },
  "night load": { th: "โหลดกลางคืน", ja: "夜間負荷", zh: "夜间负载" },
  "suspected ring-main leak": {
    th: "สงสัยว่ามีการรั่วในท่อลมวงแหวน",
    ja: "リングメイン配管の漏れの疑い",
    zh: "疑似环形主管道泄漏",
  },
  "after AI standby tuning": { th: "หลังปรับสแตนด์บายด้วย AI", ja: "AIスタンバイ調整後", zh: "经AI待机调优后" },
  "AI savings found": { th: "AI พบโอกาสประหยัด", ja: "AIが削減機会を発見", zh: "AI 发现节省空间" },
  yr: { th: "ปี", ja: "年", zh: "年" },
  "Top:": { th: "สูงสุด:", ja: "最上位:", zh: "首选:" },
  "Start saving": { th: "เริ่มประหยัด", ja: "削減を開始", zh: "开始节省" },

  /* -------------------------------------------------------------------- Live */
  "Plant Load": { th: "โหลดโรงงาน", ja: "工場負荷", zh: "厂区负载" },
  "Voltage · L-L": { th: "แรงดัน · เฟส-เฟส", ja: "電圧 · 線間", zh: "电压 · 线电压" },
  Current: { th: "กระแส", ja: "電流", zh: "电流" },
  "Power Factor": { th: "เพาเวอร์แฟกเตอร์", ja: "力率", zh: "功率因数" },
  Frequency: { th: "ความถี่", ja: "周波数", zh: "频率" },
  "Energy Digital Twin · live power flow — click a machine for its electrical parameters": {
    th: "ดิจิทัลทวินพลังงาน · การไหลของกำลังไฟแบบเรียลไทม์ — คลิกที่เครื่องจักรเพื่อดูพารามิเตอร์ทางไฟฟ้า",
    ja: "エネルギーデジタルツイン · リアルタイム電力フロー — 機械をクリックして電気パラメータを表示",
    zh: "能源数字孪生 · 实时功率流 — 点击设备查看其电气参数",
  },
  Total: { th: "รวม", ja: "合計", zh: "总计" },
  "Production Hall": { th: "โซนการผลิต", ja: "生産ホール", zh: "生产车间" },
  "Facility & Utility": { th: "ระบบสาธารณูปโภค", ja: "施設・ユーティリティ", zh: "设施与公用" },
  "On-peak": { th: "ช่วงพีค", ja: "オンピーク", zh: "峰时" },
  "Off-peak": { th: "ช่วงออฟพีค", ja: "オフピーク", zh: "谷时" },
  "Load by hour · before vs after": { th: "โหลดรายชั่วโมง · ก่อน/หลังเลื่อน", ja: "時間別負荷 · 前後比較", zh: "逐时负荷 · 前后对比" },
  "Before": { th: "ก่อนเลื่อน", ja: "移行前", zh: "移前" },
  "After shift": { th: "หลังเลื่อน", ja: "移行後", zh: "移后" },
  "Shifted out of on-peak": { th: "ย้ายออกจากช่วงพีค", ja: "オンピークから移動", zh: "移出峰时" },
  "Loads to shift · AI-recommended": { th: "โหลดที่ AI แนะนำให้เลื่อน", ja: "移行する負荷 · AI推奨", zh: "待转移负荷 · AI推荐" },
  "shifting": { th: "กำลังเลื่อน", ja: "移行中", zh: "转移中" },
  "AI pick": { th: "AI แนะนำ", ja: "AI推奨", zh: "AI推荐" },
  "You added": { th: "คุณเพิ่มเอง", ja: "手動追加", zh: "手动添加" },
  "Shifting to off-peak": { th: "เลื่อนไปออฟพีค", ja: "オフピークへ移行", zh: "转移至谷时" },
  "Paused": { th: "พัก", ja: "一時停止", zh: "暂停" },
  "Add a load yourself": { th: "เพิ่มโหลดเอง", ja: "負荷を手動追加", zh: "手动添加负荷" },
  "All loads added": { th: "เพิ่มครบทุกโหลดแล้ว", ja: "全負荷を追加済み", zh: "已添加全部负荷" },
  "load easing — stepped down to watch": {
    th: "โหลดผ่อนคลาย — ปรับลดสถานะเป็นเฝ้าระวัง",
    ja: "負荷が緩和 — 監視レベルに引き下げ",
    zh: "负载缓解 — 降级至观察",
  },
  "returned to normal": { th: "กลับสู่ภาวะปกติ", ja: "正常に復帰", zh: "恢复正常" },
  "over-draw alarm —": { th: "แจ้งเตือนกำลังไฟเกิน —", ja: "過負荷アラーム —", zh: "过载警报 —" },
  "above expected load": { th: "สูงกว่าโหลดที่คาดไว้", ja: "予測負荷を超過", zh: "高于预期负载" },
  "load rising —": { th: "โหลดกำลังเพิ่มขึ้น —", ja: "負荷が上昇中 —", zh: "负载上升 —" },
  "above baseline": { th: "สูงกว่าค่าฐาน", ja: "ベースラインを超過", zh: "高于基线" },
  "Live events": { th: "เหตุการณ์เรียลไทม์", ja: "ライブイベント", zh: "实时事件" },
  "simulated · updates every 4 s": {
    th: "จำลอง · อัปเดตทุก 4 วินาที",
    ja: "シミュレーション · 4秒ごとに更新",
    zh: "模拟 · 每4秒更新",
  },
  "Monitoring… events will appear here as machines change state.": {
    th: "กำลังตรวจสอบ… เหตุการณ์จะปรากฏที่นี่เมื่อเครื่องจักรเปลี่ยนสถานะ",
    ja: "監視中… 機械の状態変化に応じてイベントがここに表示されます。",
    zh: "监控中… 设备状态变化时事件将显示于此。",
  },

  /* -------------------------------------------------------------------- Cost */
  "Bill · MTD": { th: "ค่าไฟ · ตั้งแต่ต้นเดือน", ja: "請求額 · 月初来", zh: "电费 · 本月至今" },
  "Forecast · Month": { th: "คาดการณ์ · ทั้งเดือน", ja: "予測 · 当月", zh: "预测 · 本月" },
  "+8% vs budget": { th: "+8% เทียบงบประมาณ", ja: "+8% 予算比", zh: "+8% 对比预算" },
  "Demand Charge": { th: "ค่าความต้องการพลังไฟฟ้า", ja: "需要料金", zh: "需量电费" },
  "Cost / Unit": { th: "ต้นทุนต่อหน่วย", ja: "単位当たりコスト", zh: "单位成本" },
  "Excess-Demand Penalty": { th: "ค่าปรับความต้องการเกิน", ja: "需要超過ペナルティ", zh: "超需量罚款" },
  "Bill breakdown · this month": { th: "รายละเอียดค่าไฟ · เดือนนี้", ja: "請求内訳 · 今月", zh: "账单明细 · 本月" },
  "Demand & penalty charges are": {
    th: "ค่าความต้องการและค่าปรับคิดเป็น",
    ja: "需要料金とペナルティ料金は",
    zh: "需量与罚款费用占",
  },
  "of the bill — the biggest lever for PeakShield AI.": {
    th: "ของค่าไฟทั้งหมด — เป็นจุดที่ PeakShield AI ช่วยได้มากที่สุด",
    ja: "を占めます — PeakShield AIにとって最大の削減余地です。",
    zh: "占账单比例 — 是 PeakShield AI 最大的优化杠杆。",
  },
  "Cost per unit · 30-day": { th: "ต้นทุนต่อหน่วย · 30 วัน", ja: "単位当たりコスト · 30日間", zh: "单位成本 · 30天" },
  "−15% after AI tuning": { th: "−15% หลังปรับด้วย AI", ja: "AI調整後 −15%", zh: "AI 调优后 −15%" },

  /* ------------------------------------------------- Peak & Cost (redesign) */
  "Demand + penalty are": { th: "ค่าดีมานด์ + ค่าปรับ คิดเป็น", ja: "デマンド + ペナルティは", zh: "需量 + 罚款占" },
  "of your bill.": { th: "ของค่าไฟ", ja: "を占めます。", zh: "电费。" },
  "The": { th: "", ja: "", zh: "" },
  "monthly peak (Wed 24 · 13:42) breached the": { th: "พีครายเดือน (พุธ 24 · 13:42) เกินค่า", ja: "月間ピーク (水24 · 13:42) が超過", zh: "月度峰值 (周三24 · 13:42) 超过" },
  "contract →": { th: "สัญญา →", ja: "契約 →", zh: "合约 →" },
  "PeakShield holds peaks under contract → save": { th: "PeakShield คุมพีคให้ต่ำกว่าสัญญา → ประหยัด", ja: "PeakShieldがピークを契約内に抑制 → 節約", zh: "PeakShield 将峰值控制在合约内 → 节省" },
  "Start": { th: "เริ่ม", ja: "開始", zh: "开始" },
  "Peak Demand": { th: "ความต้องการสูงสุด", ja: "最大需要", zh: "峰值需求" },
  "Demand + Penalty": { th: "ดีมานด์ + ค่าปรับ", ja: "デマンド + ペナルティ", zh: "需量 + 罚款" },
  "of bill": { th: "ของบิล", ja: "請求比", zh: "账单占比" },
  "Load Factor": { th: "แฟกเตอร์โหลด", ja: "負荷率", zh: "负载率" },
  "Peak demand vs contract · this month": { th: "ความต้องการสูงสุด เทียบสัญญา · เดือนนี้", ja: "最大需要 対 契約 · 今月", zh: "峰值需求 对比合约 · 本月" },
  "1 breach": { th: "เกิน 1 ครั้ง", ja: "超過1回", zh: "1次超限" },
  "Contract": { th: "สัญญา", ja: "契約", zh: "合约" },
  "Target": { th: "เป้าหมาย", ja: "目標", zh: "目标" },
  "The demand charge is set by the single highest 15-min peak.": { th: "ค่าดีมานด์คิดจากพีคสูงสุดช่วง 15 นาทีเพียงครั้งเดียว", ja: "デマンド料金は最も高い15分ピーク1回で決まります。", zh: "需量电费由最高的单个15分钟峰值决定。" },
  "on the 24th cost a": { th: "เมื่อวันที่ 24 ทำให้เสียค่าปรับ", ja: "24日のスパイクで", zh: "24日的尖峰造成" },
  "penalty — one machine start pushed you over contract.": { th: "— แค่ Motor ตัวเดียวสตาร์ทก็ทำให้เกินสัญญา", ja: "のペナルティ — 機械1台の始動で契約超過。", zh: "罚款 — 仅一台设备启动就超出合约。" },
  "Demand + penalty =": { th: "ดีมานด์ + ค่าปรับ =", ja: "デマンド + ペナルティ =", zh: "需量 + 罚款 =" },
  "— the biggest controllable lever (energy is fixed by production).": { th: "— lever ที่คุมได้ใหญ่สุด (ค่าพลังงานผูกกับการผลิต)", ja: "— 最大の制御可能レバー（電力量は生産で固定）。", zh: "— 最大的可控杠杆（电量由生产决定）。" },
  "Peak shaving · PeakShield": { th: "ตัดยอดพีค · PeakShield", ja: "ピークカット · PeakShield", zh: "削峰 · PeakShield" },
  "Now": { th: "ตอนนี้", ja: "現在", zh: "当前" },
  "With PeakShield": { th: "เมื่อใช้ PeakShield", ja: "PeakShield適用時", zh: "启用 PeakShield" },
  "Penalty avoided": { th: "ค่าปรับที่เลี่ยงได้", ja: "回避したペナルティ", zh: "避免的罚款" },
  "Annualized": { th: "ต่อปี", ja: "年換算", zh: "年化" },
  "Method": { th: "วิธีการ", ja: "方法", zh: "方式" },
  "Auto-defer Air Comp + Chiller ~5 min at forecast peak": { th: "หน่วง Air Comp + Chiller ~5 นาที อัตโนมัติตอนคาดว่าจะพีค", ja: "予測ピーク時にエアコン+チラーを約5分自動抑制", zh: "预测峰值时自动延后空压机+冷水机约5分钟" },
  "Start peak shaving": { th: "เริ่มตัดยอดพีค", ja: "ピークカットを開始", zh: "开始削峰" },
  "mo": { th: "เดือน", ja: "月", zh: "月" },
  "Load shifting · TOU arbitrage": { th: "ย้ายโหลด · ไปช่วงไฟถูก", ja: "負荷シフト · TOU裁定", zh: "负荷转移 · 分时套利" },
  "On-peak rate": { th: "อัตราช่วงพีค", ja: "オンピーク単価", zh: "峰时单价" },
  "Off-peak rate": { th: "อัตราช่วงออฟพีค", ja: "オフピーク単価", zh: "谷时单价" },
  "Spread": { th: "ส่วนต่าง", ja: "差額", zh: "差价" },
  "Shift 200 kW packaging → off-peak": { th: "ย้ายงานแพ็ก 200 kW → ช่วงออฟพีค", ja: "包装200 kWをオフピークへ移行", zh: "将200 kW包装负荷 → 谷时" },
  "zero capex": { th: "ไม่ต้องลงทุน", ja: "設備投資ゼロ", zh: "零投资" },
  "Live demand · this interval": { th: "ดีมานด์สด · ช่วงเวลานี้", ja: "ライブ需要 · 当インターバル", zh: "实时需量 · 本区间" },
  "15-min block": { th: "บล็อก 15 นาที", ja: "15分ブロック", zh: "15分钟区块" },
  "Instantaneous": { th: "ค่าปัจจุบัน", ja: "瞬時値", zh: "瞬时值" },
  "15-min demand": { th: "ดีมานด์ 15 นาที", ja: "15分需要", zh: "15分钟需量" },
  "Predicted close": { th: "คาดการณ์ตอนจบ", ja: "終了時予測", zh: "收盘预测" },
  "Predicted": { th: "คาดการณ์", ja: "予測", zh: "预测" },
  "Will breach by": { th: "จะเกินสัญญา", ja: "契約超過見込み", zh: "将超限" },
  "shed load now (defer Air Comp / Chiller) to avoid setting a new peak.": { th: "ปลดโหลดตอนนี้ (หน่วง Air Comp / Chiller) เพื่อไม่ให้ตั้งพีคใหม่", ja: "今すぐ負荷遮断 (エアコン/チラーを抑制) し新ピーク設定を回避。", zh: "立即甩负荷（延后空压机/冷水机）以避免设定新峰值。" },
  "Shed now": { th: "ปลดโหลดทันที", ja: "今すぐ遮断", zh: "立即甩负荷" },
  "On track — headroom": { th: "อยู่ในเกณฑ์ — เหลือ", ja: "順調 — 余裕", zh: "正常 — 余量" },
  "to contract at interval close.": { th: "ถึงเพดานสัญญาเมื่อจบช่วง", ja: "インターバル終了時の契約値まで。", zh: "至区间结束时的合约值。" },
  "Baseline": { th: "เส้นฐาน", ja: "ベースライン", zh: "基线" },
  "days over baseline": { th: "วันที่เกินเส้นฐาน", ja: "日ベースライン超過", zh: "天超出基线" },
  "on target": { th: "อยู่ในเป้า", ja: "目標内", zh: "达标" },
  "cost ceiling — should not exceed": { th: "เพดานต้นทุน — ไม่ควรเกิน", ja: "コスト上限 — 超えないこと", zh: "成本上限 — 不应超过" },
  "Bill breakdown": { th: "รายละเอียดค่าไฟ", ja: "請求内訳", zh: "账单明细" },
  "MTD": { th: "ตั้งแต่ต้นเดือน", ja: "月初来", zh: "本月至今" },
  "6-month bill history · click to view": { th: "ประวัติค่าไฟ 6 เดือน · คลิกเพื่อดู", ja: "6ヶ月の請求履歴 · クリックで表示", zh: "6个月账单历史 · 点击查看" },
  "Shiftable loads": { th: "โหลดที่ย้ายได้", ja: "シフト可能負荷", zh: "可转移负荷" },
  "Packaging line": { th: "ไลน์แพ็กเกจ", ja: "包装ライン", zh: "包装线" },
  "Compressed-air charging": { th: "อัดลมเข้าถัง", ja: "圧縮空気充填", zh: "压缩空气充气" },
  "Chiller pre-cooling": { th: "ทำความเย็นล่วงหน้า (Chiller)", ja: "チラー予冷", zh: "冷水机预冷" },

  /* ------------------------------------------------------------ Opportunity */
  "AI-discovered savings opportunities": {
    th: "โอกาสประหยัดที่ AI ค้นพบ",
    ja: "AIが発見した削減機会",
    zh: "AI 发现的节省机会",
  },
  "Ask AI where to start": { th: "ถาม AI ว่าควรเริ่มจากตรงไหน", ja: "どこから始めるかAIに尋ねる", zh: "询问 AI 从何入手" },
  "Peak Optimization": { th: "การปรับพีคให้เหมาะสม", ja: "ピーク最適化", zh: "峰值优化" },
  "Compressor Sequencing": { th: "การจัดลำดับ Compressor", ja: "コンプレッサー順序制御", zh: "压缩机排序控制" },
  "Chiller Optimization": { th: "การปรับ Chiller ให้เหมาะสม", ja: "チラー最適化", zh: "冷水机组优化" },
  "Idle Machine Shutdown": { th: "การปิดเครื่องจักรที่เดินตัวเปล่า", ja: "アイドル機械の停止", zh: "闲置设备关停" },
  "Automated load-shed + pre-cooling off-peak.": {
    th: "การปลดโหลดอัตโนมัติ + การทำความเย็นล่วงหน้าช่วงออฟพีค",
    ja: "自動負荷制限 + オフピーク時の予冷。",
    zh: "自动减载 + 谷时预冷。",
  },
  "Lead/lag staging to match air demand.": {
    th: "การสลับลำดับหลัก/รองให้ตรงกับความต้องการลม",
    ja: "空気需要に合わせたリード/ラグ段階制御。",
    zh: "主/辅分级以匹配用气需求。",
  },
  "Setpoint + staging tuning across the plant.": {
    th: "การปรับค่าตั้งและการจัดลำดับทั่วทั้งโรงงาน",
    ja: "工場全体のセットポイントと段階制御の調整。",
    zh: "全厂设定点与分级调优。",
  },
  "Auto-standby for machines idling >15 min.": {
    th: "พักเครื่องอัตโนมัติเมื่อเดินตัวเปล่าเกิน 15 นาที",
    ja: "15分以上アイドルの機械を自動スタンバイ。",
    zh: "空转超过15分钟的设备自动待机。",
  },

  /* ------------------------------------------------- Savings (portfolio + M&V) */
  "identified across": { th: "ระบุได้จาก", ja: "特定 ·", zh: "识别自" },
  "measures.": { th: "มาตรการ", ja: "件の施策。", zh: "项措施。" },
  "already active — ": { th: "ทำงานอยู่แล้ว — ", ja: "既に稼働中 — ", zh: "已启用 — " },
  "banked YTD (verified).": { th: "ประหยัดจริงสะสมปีนี้ (ยืนยันแล้ว)", ja: "年初来実績 (検証済み)。", zh: "年初至今已实现 (已验证)。" },
  "zero-capex measures are ready to deploy today.": { th: "มาตรการไม่ต้องลงทุน พร้อมกดใช้วันนี้", ja: "投資ゼロの施策が本日展開可能。", zh: "零投资措施今日即可部署。" },
  "Prioritize": { th: "จัดลำดับ", ja: "優先順位付け", zh: "排优先级" },
  "Savings captured": { th: "เงินที่ประหยัดได้แล้ว", ja: "実現済み節約", zh: "已捕获节省" },
  "captured": { th: "ทำงานอยู่", ja: "実現", zh: "已捕获" },
  "Savings portfolio · ranked by payback": { th: "รวมมาตรการประหยัด · จัดเรียงตามความคุ้มค่า", ja: "節約ポートフォリオ · 回収期間順", zh: "节省组合 · 按回收期排序" },
  "Measure": { th: "มาตรการ", ja: "施策", zh: "措施" },
  "Savings/yr": { th: "ประหยัด/ปี", ja: "節約/年", zh: "节省/年" },
  "from:": { th: "ที่มา:", ja: "出典:", zh: "来源：" },
  "findings from meter data.": { th: "รา·ารที่เจอจากข้อมูลมิเตอร์", ja: "件をメーターデータから検出。", zh: "项来自电表数据的发现。" },
  "being realized — ": { th: "กำลังทำได้จริง — ", ja: "実現進行中 — ", zh: "正在实现 — " },
  "critical findings need action now.": { th: "รา·ารวิกฤตต้องแก้ทันที", ja: "件の重大項目が即対応必要。", zh: "项严重发现需立即处理。" },
  "realized": { th: "ทำได้จริง", ja: "実現", zh: "已实现" },
  "Realized · run-rate": { th: "ทำได้จริง · อัตราต่อปี", ja: "実現 · 年換算", zh: "已实现 · 年化" },
  "Priority": { th: "ความสำคัญ", ja: "優先度", zh: "优先级" },
  "from meter": { th: "จากมิเตอร์", ja: "メーターから", zh: "来自电表" },
  "Demand charge 34% of bill · monthly peak 3,150 kW over contract": { th: "ค่าดีมานด์ 34% ของบิล · พีครายเดือน 3,150 kW เกินสัญญา", ja: "デマンド料金が請求の34% · 月間ピーク3,150 kWが契約超過", zh: "需量电费占账单34% · 月度峰值3,150 kW超合约" },
  "Metered idle draw 128 kWh/day across 6 machines": { th: "วัดไฟตอนเดินตัวเปล่าได้ 128 kWh/วัน จาก 6 เครื่อง", ja: "6台でアイドル消費128 kWh/日を計測", zh: "计量6台设备空转耗电128 kWh/天" },
  "Air demand vs supply mismatch · 2 compressors poorly staged": { th: "ความต้องการลมกับกำลังจ่ายไม่สมดุล · Compressor 2 ตัวจัดลำดับไม่ดี", ja: "空気需要と供給の不一致 · コンプレッサ2台の段階制御が不良", zh: "用气需求与供给不匹配 · 2台压缩机分级不佳" },
  "Chiller kW/ton 12% over design · setpoint drift": { th: "Chiller kW/ton สูงกว่าค่าออกแบบ 12% · ค่าตั้งเพี้ยน", ja: "チラーkW/tonが設計比12%超 · 設定値ドリフト", zh: "冷水机kW/ton超设计12% · 设定值漂移" },
  "Equipment audit · 4,200 legacy fixtures · AHU without VSD": { th: "ตรวจอุปกรณ์ · โคมไฟเก่า 4,200 จุด · AHU ไม่มี VSD", ja: "設備監査 · 旧型器具4,200台 · VSD無しAHU", zh: "设备审计 · 4,200个旧灯具 · AHU无变频" },
  "2,400 m² usable roof · 68% of load is daytime on-peak": { th: "หลังคาใช้ได้ 2,400 ตร.ม. · 68% ของโหลดคือช่วงพีคกลางวัน", ja: "利用可能屋根2,400 m² · 負荷の68%が日中オンピーク", zh: "可用屋顶2,400 m² · 68%负荷为白天峰时" },
  "Status": { th: "สถานะ", ja: "状態", zh: "状态" },
  "Identified": { th: "ระบุได้", ja: "特定済み", zh: "已识别" },
  "Active · captured": { th: "ทำงานอยู่ · ประหยัดจริง", ja: "稼働中 · 実現", zh: "已启用 · 已捕获" },
  "Banked · YTD": { th: "สะสม · ปีนี้", ja: "実績 · 年初来", zh: "已实现 · 年初至今" },
  "Remaining": { th: "คงเหลือ", ja: "残り", zh: "剩余" },
  "Realized savings vs baseline · YTD": { th: "เงินที่ประหยัดได้จริงเทียบฐาน · ปีนี้", ja: "ベースライン比 実現節約 · 年初来", zh: "相对基线的已实现节省 · 年初至今" },
  "verified · M&V": { th: "ยืนยันแล้ว · M&V", ja: "検証済み · M&V", zh: "已验证 · M&V" },
  "banked year-to-date vs the pre-AI baseline": { th: "ประหยัดสะสมปีนี้เทียบฐานก่อนใช้ AI", ja: "AI導入前ベースライン比の年初来実績", zh: "相对AI前基线的年初至今节省" },
  "current run-rate": { th: "อัตราปัจจุบัน", ja: "現在のランレート", zh: "当前年化率" },
  "Savings compound as more measures go live — each bar is verified against metered baseline, not estimated.": { th: "เงินประหยัดทบต้นเมื่อมาตรการทยอ·ำงาน — แต่ละแท่งยืนยันเทียบมิเตอร์จริง ไม่ใช่ประมาณการ", ja: "施策が稼働するほど節約が積み上がります — 各バーは推定ではなく計量ベースラインで検証済み。", zh: "随更多措施上线，节省逐步累积 — 每根柱均按计量基线验证，非估算。" },
  "Marginal abatement cost · cheapest first": { th: "ต้นทุนลดหน่วยส่วนเพิ่ม · คุ้มสุดก่อน", ja: "限界削減費用 · 安い順", zh: "边际减排成本 · 最省优先" },
  "< 6 mo payback": { th: "คืนทุน < 6 เดือน", ja: "回収 < 6ヶ月", zh: "回收 < 6个月" },
  "< 2 yr": { th: "< 2 ปี", ja: "< 2年", zh: "< 2年" },
  "capital": { th: "ต้องลงทุน", ja: "設備投資", zh: "需投资" },
  "bar height = payback · width = ฿/yr": { th: "ความสูง = ระยะคืนทุน · ความกว้าง = ฿/ปี", ja: "高さ = 回収期間 · 幅 = ฿/年", zh: "柱高 = 回收期 · 柱宽 = ฿/年" },
  "Quick wins · zero capex · deploy today": { th: "ทำได้เลย · ไม่ต้องลงทุน · กดใช้วันนี้", ja: "クイックウィン · 投資ゼロ · 本日展開", zh: "速赢 · 零投资 · 今日部署" },
  "Capital projects · simulate ROI": { th: "โปรเจกต์ลงทุน · จำลอง ROI", ja: "資本プロジェクト · ROIシミュレーション", zh: "资本项目 · 模拟ROI" },
  "Capex": { th: "เงินลงทุน", ja: "設備投資", zh: "投资" },
  "Payback": { th: "คืนทุน", ja: "回収期間", zh: "回收期" },
  "Confidence": { th: "ความมั่นใจ", ja: "信頼度", zh: "置信度" },
  "Zero": { th: "ไม่มี", ja: "ゼロ", zh: "零" },
  "Instant": { th: "ทันที", ja: "即時", zh: "即时" },
  "Auto-running": { th: "ทำงานอัตโนมัติ", ja: "自動稼働中", zh: "自动运行中" },
  "Live in AI Optimization": { th: "กำลังทำงานใน AI Optimization", ja: "AI最適化で稼働中", zh: "在AI优化中运行" },
  "Running in AI Optimization": { th: "กำลังทำงานใน AI Optimization", ja: "AI最適化で実行中", zh: "正在AI优化中运行" },
  "ROI in Savings": { th: "ดู ROI ใน Savings", ja: "SavingsでROIを見る", zh: "在Savings查看ROI" },
  "Deploy": { th: "กดใช้งาน", ja: "展開", zh: "部署" },
  "Simulate ROI": { th: "จำลอง ROI", ja: "ROIをシミュレート", zh: "模拟ROI" },
  "Active · capturing": { th: "ทำงานอยู่ · กำลังประหยัด", ja: "稼働中 · 実現中", zh: "运行中 · 捕获中" },
  "Ready to deploy": { th: "พร้อมกดใช้", ja: "展開準備完了", zh: "可部署" },
  "Planned": { th: "วางแผนไว้", ja: "計画中", zh: "已规划" },
  "LED + HVAC Retrofit": { th: "เปลี่ยน LED + ปรับปรุง HVAC", ja: "LED + HVAC 改修", zh: "LED + 暖通改造" },
  "Solar Rooftop 500 kWp": { th: "โซลาร์รูฟท็อป 500 kWp", ja: "屋上太陽光 500 kWp", zh: "屋顶光伏 500 kWp" },
  "Facility lighting + AHU VSD upgrade.": { th: "ไฟส่องสว่างโรงงาน + ติด VSD ที่ AHU", ja: "施設照明 + AHU VSD 更新。", zh: "厂区照明 + AHU变频升级。" },
  "Offset daytime on-peak with PV.": { th: "ชดเชยโหลดช่วงพีคกลางวันด้วยโซลาร์", ja: "日中オンピークをPVで相殺。", zh: "用光伏抵消白天峰时用电。" },

  /* ------------------------------------------ AI Optimization (redesign) */
  "The AI is optimizing your energy right now": { th: "AI กำลังปรับพลังงานให้คุณอยู่ตอนนี้", ja: "AIが今エネルギーを最適化中", zh: "AI 正在为您优化能源" },
  "Saved · this month": { th: "ประหยัด · เดือนนี้", ja: "節約 · 今月", zh: "节省 · 本月" },
  "Saved · today": { th: "ประหยัด · วันนี้", ja: "節約 · 本日", zh: "节省 · 今日" },
  "Run-rate": { th: "อัตราต่อเนื่อง", ja: "ランレート", zh: "年化率" },
  "Autonomy level": { th: "ระดับการทำงานอัตโนมัติ", ja: "自律レベル", zh: "自主级别" },
  "Advisory": { th: "แนะนำ", ja: "アドバイザリー", zh: "仅建议" },
  "Approve each": { th: "อนุมัติทีละครั้ง", ja: "都度承認", zh: "逐项审批" },
  "Full-auto": { th: "อัตโนมัติเต็ม", ja: "完全自動", zh: "全自动" },
  "AI only recommends — you run every action.": { th: "AI แค่แนะนำ — คุณเป็นคนสั่งทุกอย่าง", ja: "AIは提案のみ — 実行はすべてあなた。", zh: "AI 仅建议 — 每项均由您执行。" },
  "AI runs actions after your one-tap approval.": { th: "AI ทำหลังคุณกดอนุมัติครั้งเดียว", ja: "ワンタップ承認後にAIが実行。", zh: "一键批准后由 AI 执行。" },
  "AI runs guardrailed actions automatically — you're notified.": { th: "AI ทำงานภายใต้กรอบอัตโนมัติ — แจ้งให้คุณทราบ", ja: "ガードレール内でAIが自動実行 — 通知します。", zh: "AI 在护栏内自动执行 — 并通知您。" },
  "Optimization actions": { th: "การดำเนินการปรับให้เหมาะสม", ja: "最適化アクション", zh: "优化操作" },
  "awaiting you": { th: "รอคุณ", ja: "対応待ち", zh: "待您处理" },
  "Runs today": { th: "ทำงานวันนี้", ja: "本日実行", zh: "今日运行" },
  "Last": { th: "ล่าสุด", ja: "最終", zh: "最近" },
  "AI activity": { th: "กิจกรรมของ AI", ja: "AIアクティビティ", zh: "AI 活动" },
  "live · audit trail": { th: "สด · บันทึกตรวจสอบ", ja: "ライブ · 監査証跡", zh: "实时 · 审计追踪" },
  "Guardrails · always on": { th: "กรอบความปลอดภัย · เปิดตลอด", ja: "ガードレール · 常時有効", zh: "安全护栏 · 始终开启" },
  "The AI operates only within these limits. You can pause any action instantly.": { th: "AI ทำงานภายในกรอบนี้เท่านั้น คุณหยุด action ใดก็ได้ทันที", ja: "AIはこの範囲内でのみ動作。いつでも任意の操作を停止できます。", zh: "AI 仅在这些限制内运行。您可随时立即暂停任何操作。" },
  "Critical production loads are never shed": { th: "ไม่ปลดโหลดการผลิตวิกฤตเด็ดขาด", ja: "重要な生産負荷は決して遮断しない", zh: "绝不切除关键生产负荷" },
  "Process temperatures held within ±1°C": { th: "คุมอุณหภูมิกระบวนการภายใน ±1°C", ja: "プロセス温度を±1°C以内に維持", zh: "工艺温度控制在 ±1°C 内" },
  "Power factor kept between 0.95–0.99": { th: "คุมเพาเวอร์แฟกเตอร์ 0.95–0.99", ja: "力率を0.95〜0.99に維持", zh: "功率因数保持 0.95–0.99" },
  "Every action is logged and reversible": { th: "ทุก action ถูกบันทึกและย้อนกลับได้", ja: "全操作は記録され取り消し可能", zh: "所有操作均记录且可撤销" },
  "Never sheds critical production loads": { th: "ไม่ปลดโหลดการผลิตวิกฤต", ja: "重要生産負荷は遮断しない", zh: "不切除关键生产负荷" },
  "Holds process temperature ±1°C": { th: "คุมอุณหภูมิกระบวนการ ±1°C", ja: "プロセス温度±1°Cを維持", zh: "保持工艺温度 ±1°C" },
  "Skips machines with queued jobs": { th: "ข้ามเครื่องที่มีงานค้าง", ja: "ジョブ待ちの機械はスキップ", zh: "跳过有排队作业的设备" },
  "Keeps power factor 0.95–0.99": { th: "คุมเพาเวอร์แฟกเตอร์ 0.95–0.99", ja: "力率0.95〜0.99を維持", zh: "保持功率因数 0.95–0.99" },
  "Deferred Air Comp 10 for 6 min — avoided a 180 kW peak.": { th: "หน่วง Air Comp 10 ไป 6 นาที — เลี่ยงพีค 180 kW", ja: "Air Comp 10を6分抑制 — 180 kWピークを回避。", zh: "延后 Air Comp 10 六分钟 — 避免 180 kW 峰值。" },
  "Charged the chilled-water loop to 6°C before on-peak.": { th: "ทำความเย็นลูปน้ำเย็นถึง 6°C ก่อนช่วงพีค", ja: "オンピーク前に冷水ループを6°Cまで蓄冷。", zh: "峰前将冷冻水回路降至 6°C。" },
  "Trimmed 2 non-critical AHUs during a forecast peak.": { th: "ลดโหลด AHU ที่ไม่วิกฤต 2 ตัวช่วงคาดว่าจะพีค", ja: "予測ピーク時に非重要AHU2台を抑制。", zh: "预测峰值时削减 2 台非关键 AHU。" },
  "Pre-cool cycle done — 1,100 kWh shifted off-peak.": { th: "รอบทำความเย็นล่วงหน้าเสร็จ — ย้าย 1,100 kWh ไปช่วงออฟพีค", ja: "予冷サイクル完了 — 1,100 kWhをオフピークへ移行。", zh: "预冷循环完成 — 1,100 kWh 转至谷时。" },
  "Held the plant under 2,950 kW through the morning ramp.": { th: "คุมทั้งโรงงานต่ำกว่า 2,950 kW ตลอดช่วงเร่งเช้า", ja: "朝の立ち上げ中、工場を2,950 kW以下に維持。", zh: "在早间爬坡期间将全厂保持在 2,950 kW 以下。" },

  /* ------------------------------------------------------------- Autonomous */
  "Autonomous Energy": { th: "พลังงานอัตโนมัติ", ja: "自律型エネルギー", zh: "自主能源" },
  "Energy actions the AI runs — with approval": {
    th: "การดำเนินการพลังงานที่ AI ทำ — เมื่อได้รับอนุมัติ",
    ja: "AIが実行するエネルギー施策 — 承認付き",
    zh: "AI 执行的能源操作 — 需审批",
  },
  running: { th: "กำลังทำงาน", ja: "実行中", zh: "运行中" },
  Running: { th: "กำลังทำงาน", ja: "実行中", zh: "运行中" },
  "Pending approval": { th: "รออนุมัติ", ja: "承認待ち", zh: "待审批" },
  Suggested: { th: "แนะนำ", ja: "提案", zh: "建议" },
  Pause: { th: "หยุดชั่วคราว", ja: "一時停止", zh: "暂停" },
  Approve: { th: "อนุมัติ", ja: "承認", zh: "批准" },
  Enable: { th: "เปิดใช้งาน", ja: "有効化", zh: "启用" },
  "Guardrailed with a full audit trail. Critical actions always need approval.": {
    th: "มีการควบคุมความปลอดภัยพร้อมบันทึกตรวจสอบครบถ้วน การดำเนินการสำคัญต้องได้รับอนุมัติเสมอ",
    ja: "完全な監査証跡付きのガードレールを備えています。重要な操作は常に承認が必要です。",
    zh: "配备完整审计追踪的安全护栏。关键操作始终需要审批。",
  },
  "Peak Load Shedding": { th: "การปลดโหลดช่วงพีค", ja: "ピーク負荷制限", zh: "峰值减载" },
  "Off-Peak Pre-Cooling": { th: "การทำความเย็นล่วงหน้าช่วงออฟพีค", ja: "オフピーク予冷", zh: "谷时预冷" },
  "Idle Auto-Standby": { th: "สแตนด์บายอัตโนมัติเมื่อเดินตัวเปล่า", ja: "アイドル自動スタンバイ", zh: "闲置自动待机" },
  "Power-Factor Correction": { th: "การแก้ไขเพาเวอร์แฟกเตอร์", ja: "力率改善", zh: "功率因数校正" },
  "Shed non-critical loads to stay under 3,000 kW.": {
    th: "ปลดโหลดที่ไม่จำเป็นเพื่อรักษาระดับต่ำกว่า 3,000 kW",
    ja: "重要でない負荷を制限し3,000 kW以下を維持します。",
    zh: "切除非关键负载以保持在 3,000 kW 以下。",
  },
  "Pre-cool chilled-water loop during off-peak tariff.": {
    th: "ทำความเย็นล่วงหน้าในวงจรน้ำเย็นช่วงอัตราออฟพีค",
    ja: "オフピーク料金時間帯に冷水ループを予冷します。",
    zh: "在谷时电价时段对冷冻水回路预冷。",
  },
  "Put machines idling >15 min into standby.": {
    th: "ตั้งเครื่องที่เดินตัวเปล่า >15 นาทีให้เข้าสู่โหมดสแตนด์บาย",
    ja: "15分以上アイドルの機械をスタンバイにします。",
    zh: "将空转超过15分钟的设备转入待机。",
  },
  "Auto-switch capacitor banks to hold PF ≥ 0.95.": {
    th: "สลับชุดคาปาซิเตอร์อัตโนมัติเพื่อรักษา PF ≥ 0.95",
    ja: "コンデンサーバンクを自動切替しPF ≥ 0.95を維持します。",
    zh: "自动切换电容器组以保持 PF ≥ 0.95。",
  },

  /* -------------------------------------------- power-meter findings board */
  "Findings & recommendations": { th: "ปัญหาที่พบ & ข้อเสนอแนะ", ja: "検出事項と推奨", zh: "发现与建议" },
  "From SpareX power-meter data": { th: "จากข้อมูลมิเตอร์ SpareX", ja: "SpareX電力計データより", zh: "来自 SpareX 电力计数据" },
  "Energy Saving Potential": { th: "ศักยภาพการประหยัดพลังงาน", ja: "省エネポテンシャル", zh: "节能潜力" },
  "Uncovered by your installed meters · ranked by impact": { th: "ค้นพบจากมิเตอร์ที่ติดตั้งไว้ · จัดลำดับตามผลกระทบ", ja: "設置済みメーターが検出 · 影響度順", zh: "由已安装电表发现 · 按影响排序" },
  "Autonomous execution": { th: "การทำงานอัตโนมัติ", ja: "自律実行", zh: "自主执行" },
  "What the AI runs automatically right now": { th: "สิ่งที่ AI ทำงานอัตโนมัติอยู่ตอนนี้", ja: "AIが現在自動実行している内容", zh: "AI 当前自动运行的内容" },
  "Issues detected · ranked by return": { th: "ปัญหาที่ตรวจพบ · จัดเรียงตามความคุ้มค่า", ja: "検出された問題 · 収益順", zh: "检测到的问题 · 按回报排序" },
  "Issues found": { th: "ปัญหาที่พบ", ja: "検出件数", zh: "发现问题" },
  "critical": { th: "วิกฤต ต้องแก้ด่วน", ja: "重大 (要至急対応)", zh: "严重 需紧急处理" },
  "Investment to fix all": { th: "งบลงทุนแก้ทั้งหมด", ja: "全対策の投資額", zh: "全部整改投资" },
  "Annual saving": { th: "ประหยัดต่อปี", ja: "年間削減額", zh: "年度节省" },
  "Blended payback": { th: "ระยะคืนทุนเฉลี่ย", ja: "平均回収期間", zh: "综合回收期" },
  "CO₂ avoided": { th: "ลดการปล่อย CO₂", ja: "CO₂削減", zh: "减少 CO₂" },
  "Request full proposal → SpareX": { th: "ขอใบเสนอราคาทั้งโครงการ → SpareX", ja: "全体提案を依頼 → SpareX", zh: "索取整体方案 → SpareX" },
  "Detected issues": { th: "ปัญหาที่ตรวจพบ", ja: "検出された問題", zh: "检测到的问题" },
  "All": { th: "ทั้งหมด", ja: "すべて", zh: "全部" },
  "Critical": { th: "วิกฤต", ja: "重大", zh: "严重" },
  "Warning": { th: "เตือน", ja: "警告", zh: "警告" },
  "The problem · from the meter": { th: "ปัญหาที่พบ · จากมิเตอร์", ja: "問題 · 電力計データ", zh: "问题 · 来自电力计" },
  "Measured": { th: "ค่าที่วัดได้", ja: "実測値", zh: "实测值" },
  "Limit": { th: "เกณฑ์", ja: "基準値", zh: "限值" },
  "Root-cause analysis": { th: "การวิเคราะห์สาเหตุ (RCA)", ja: "根本原因分析 (RCA)", zh: "根因分析 (RCA)" },
  "Business impact": { th: "ผลกระทบต่อธุรกิจ", ja: "事業への影響", zh: "业务影响" },
  "AI recommendation": { th: "AI แนะนำแนวทางแก้ไข", ja: "AIの推奨対策", zh: "AI 建议方案" },
  "Parts & specification": { th: "อุปกรณ์ & สเปก", ja: "部品と仕様", zh: "部件与规格" },
  "No hardware change — setpoint / software only": { th: "ไม่ต้องเปลี่ยนอุปกรณ์ — ปรับตั้งค่า/ซอฟต์แวร์เท่านั้น", ja: "ハード変更なし — 設定/ソフトのみ", zh: "无需更换硬件 — 仅调整设定/软件" },
  "Item": { th: "รา·าร", ja: "品目", zh: "项目" },
  "Spec": { th: "สเปก", ja: "仕様", zh: "规格" },
  "Qty": { th: "จำนวน", ja: "数量", zh: "数量" },
  "Unit price": { th: "ราคาต่อหน่วย", ja: "単価", zh: "单价" },
  "Amount": { th: "ยอดรวม", ja: "金額", zh: "金额" },
  "Parts subtotal": { th: "รวมค่าอุปกรณ์", ja: "部品小計", zh: "部件小计" },
  "incl. installation & commissioning": { th: "รวมค่าติดตั้ง & ทดสอบระบบ", ja: "設置・試運転含む", zh: "含安装与调试" },
  "Investment": { th: "เงินลงทุน", ja: "投資額", zh: "投资额" },
  "Return / yr": { th: "ผลตอบแทน/ปี", ja: "年間リターン", zh: "年回报率" },
  "5-yr net": { th: "กำไรสุทธิ 5 ปี", ja: "5年純益", zh: "5年净收益" },
  "Approve & schedule": { th: "อนุมัติแผนซ่อม", ja: "修理計画を承認", zh: "批准维修计划" },
  "Request quotation": { th: "ขอใบเสนอราคา", ja: "見積を依頼", zh: "索取报价" },
  "New": { th: "ใหม่", ja: "新規", zh: "新" },
  "Approved & scheduled": { th: "อนุมัติแล้ว · จัดคิว", ja: "承認済み · 予定", zh: "已批准 · 排期" },
  "Quote requested": { th: "ขอราคาแล้ว", ja: "見積依頼済み", zh: "已询价" },
  "Detected": { th: "ตรวจพบเมื่อ", ja: "検出日時", zh: "检测于" },
  "Meter": { th: "มิเตอร์", ja: "電力計", zh: "电力计" },
  /* quote modal */
  "Request quotation — to SpareX sales": { th: "ขอใบเสนอราคา — ส่งถึงทีมขาย SpareX", ja: "見積依頼 — SpareX営業へ", zh: "索取报价 — 发送至 SpareX 销售" },
  "SpareX prepares a firm quote for the parts and installation below.": { th: "SpareX จะจัดทำใบเสนอราคาจริงสำหรับอุปกรณ์และการติดตั้งด้านล่าง", ja: "SpareXが下記の部品と設置の正式見積を作成します。", zh: "SpareX 将为以下部件与安装准备正式报价。" },
  "Included measures": { th: "รา·ารที่ขอราคา", ja: "対象施策", zh: "所含措施" },
  "line items": { th: "รา·ารอุปกรณ์", ja: "明細", zh: "明细项" },
  "Total investment": { th: "มูลค่าลงทุนรวม", ja: "投資総額", zh: "投资总额" },
  "Your details": { th: "ข้อมูลผู้ติดต่อ", ja: "ご連絡先", zh: "您的信息" },
  "Contact name": { th: "ชื่อผู้ติดต่อ", ja: "担当者名", zh: "联系人" },
  "Company / site": { th: "บริษัท / ไซต์", ja: "会社 / 拠点", zh: "公司 / 现场" },
  "Email": { th: "อีเมล", ja: "メール", zh: "邮箱" },
  "Phone": { th: "เบอร์โทร", ja: "電話", zh: "电话" },
  "Note to SpareX (optional)": { th: "หมายเหตุถึง SpareX (ไม่บังคับ)", ja: "SpareXへのメモ (任意)", zh: "给 SpareX 的备注（可选）" },
  "Cancel": { th: "·เลิก", ja: "キャンセル", zh: "取消" },
  "Send request": { th: "ส่งคำขอ", ja: "依頼を送信", zh: "发送请求" },
  "Sending…": { th: "กำลังส่ง…", ja: "送信中…", zh: "发送中…" },
  "Request sent to SpareX": { th: "ส่งคำขอถึง SpareX แล้ว", ja: "SpareXへ送信しました", zh: "已发送至 SpareX" },
  "Reference": { th: "เลขอ้างอิง", ja: "参照番号", zh: "参考编号" },
  "The SpareX sales team will get back to you within 1 business day.": { th: "ทีมขาย SpareX จะติดต่อกลับภายใน 1 วันทำการ", ja: "SpareX営業チームが1営業日以内にご連絡します。", zh: "SpareX 销售团队将在 1 个工作日内与您联系。" },
  "A copy has been logged to the audit trail.": { th: "บันทึกสำเนาไว้ในประวัติการทำงานแล้ว", ja: "監査証跡に記録されました。", zh: "副本已记录到审计追踪。" },
  "Done": { th: "เสร็จสิ้น", ja: "完了", zh: "完成" },
  "Ask AI about this": { th: "ถาม AI เพิ่มเติม", ja: "AIにもっと聞く", zh: "向 AI 追问" },
  /* severity — descriptive labels (chip uses these; colored dot = the traffic light) */
  "Critical · fix now": { th: "วิกฤต · แก้ด่วน", ja: "重大 · 至急対応", zh: "严重 · 立即处理" },
  "Warning · this month": { th: "ติดตาม · ภายในเดือนนี้", ja: "注意 · 今月中", zh: "关注 · 本月内" },
  "Advisory · improve": { th: "แนะนำ · ปรับปรุงเพิ่ม", ja: "推奨 · 追加改善", zh: "建议 · 进一步优化" },
  "Monitor": { th: "ติดตาม", ja: "注意", zh: "关注" },
  /* metric verdict (over / near / within threshold) */
  "Over threshold": { th: "⚠️ เกินเกณฑ์", ja: "⚠️ 基準超過", zh: "⚠️ 超标" },
  "Near threshold": { th: "⚠️ ใกล้เกณฑ์", ja: "⚠️ 基準に接近", zh: "⚠️ 接近上限" },
  "OK · within limit": { th: "✅ ปกติ", ja: "✅ 正常", zh: "✅ 正常" },
  /* root cause — numbered "steps" framing */
  "Where it starts": { th: "จุดเริ่มของปัญหา", ja: "問題の起点", zh: "问题起点" },
  "CO₂ emissions cut": { th: "ลดการปล่อย CO₂", ja: "CO₂排出削減", zh: "减少 CO₂ 排放" },
  "critical · urgent": { th: "วิกฤต ต้องแก้ด่วน", ja: "重大・要至急", zh: "严重 需紧急" },
  "Financial summary": { th: "สรุปผลตอบแทนการลงทุน", ja: "財務サマリー", zh: "财务摘要" },
  "Measured data": { th: "ค่าที่วัดได้จากมิเตอร์", ja: "実測データ", zh: "实测数据" },
  /* friendly report headers (easy-to-understand redesign) */
  "What we found": { th: "ปัญหาที่เจอ", ja: "検出した問題", zh: "发现的问题" },
  "Why it happens": { th: "ต้นเหตุ", ja: "原因", zh: "原因" },
  "If left unfixed": { th: "ถ้าปล่อยไว้ไม่แก้", ja: "放置した場合", zh: "若不处理" },
  "If you do nothing": { th: "ถ้าปล่อยไว้ไม่แก้", ja: "何もしない場合", zh: "若不处理" },
  "If you invest to fix": { th: "ถ้าลงทุนแก้", ja: "投資して修正する場合", zh: "若投资修复" },
  "Money lost": { th: "เงินที่เสียไปเปล่าๆ", ja: "損失額", zh: "损失金额" },
  "Invest": { th: "ลงทุน", ja: "投資", zh: "投资" },
  "Zero Invest": { th: "ไม่ต้องลงทุน", ja: "投資ゼロ", zh: "零投资" },
  "free": { th: "ฟรี", ja: "無償", zh: "免费" },
  "Live peak shaving": { th: "ลดพีคแบบเรียลไทม์", ja: "リアルタイムピークカット", zh: "实时削峰" },
  "AI holding demand under the contract cap, in real time": { th: "AI กดพีคไม่ให้เกินสัญญา แบบเรียลไทม์", ja: "AIが契約上限以下にデマンドをリアルタイム制御", zh: "AI 实时将需量控制在合约上限以下" },
  "AI-managed": { th: "AI คุมอยู่", ja: "AI制御中", zh: "AI 已管控" },
  "Without AI": { th: "ถ้าไม่มี AI", ja: "AIなしの場合", zh: "若无 AI" },
  "Shaved now": { th: "ลดได้ตอนนี้", ja: "現在のカット量", zh: "当前削减" },
  "Bill Impact Simulator": { th: "จำลองผลต่อค่าไฟ", ja: "電気代インパクト・シミュレーター", zh: "电费影响模拟器" },
  "Toggle the levers — watch this month's bill move": { th: "สลับสวิตช์ — ดูค่าไฟเดือนนี้ขยับ", ja: "レバーを切り替えて今月の電気代の変化を確認", zh: "切换开关 — 看本月电费变化" },
  "Current bill": { th: "ค่าไฟตอนนี้", ja: "現在の請求額", zh: "当前电费" },
  "Optimized bill": { th: "ค่าไฟหลังปรับ", ja: "最適化後の請求額", zh: "优化后电费" },
  "How to fix it (AI)": { th: "วิธีแก้ที่ AI แนะนำ", ja: "AIの解決策", zh: "AI 建议方案" },
  "Parts needed": { th: "อุปกรณ์ที่ต้องใช้", ja: "必要な部品", zh: "所需部件" },
  "Rough budget": { th: "งบประมาณคร่าวๆ", ja: "概算予算", zh: "预算概估" },
  "Estimate only · final price on SpareX quotation": { th: "ประมาณการ · ราคาจริงยืนยันตอนขอใบเสนอราคาจาก SpareX", ja: "概算 · 正式価格はSpareX見積時に確定", zh: "仅为估算 · 最终价格以SpareX报价为准" },
  "Is it worth it?": { th: "ลงทุนแล้วคุ้มไหม", ja: "投資対効果は？", zh: "是否值得投资" },
  "Excellent payback": { th: "คุ้มมาก", ja: "回収が非常に良い", zh: "回报优秀" },
  "Good payback": { th: "คุ้มค่า", ja: "回収良好", zh: "回报良好" },
  "Long-term investment": { th: "ลงทุนระยะยาว", ja: "長期投資", zh: "长期投资" },
  /* energy management control tools */
  "Energy management tools": { th: "เครื่องมือจัดการพลังงาน", ja: "エネルギー管理ツール", zh: "能源管理工具" },
  "Hands-on controls to run these measures yourself": { th: "ควบคุมและสั่งการมาตรการเหล่านี้ได้ด้วยตัวเอง", ja: "これらの施策を手動で運用するコントロール", zh: "手动运行这些措施的控制工具" },
  "Adjust operations · no investment": { th: "ปรับการทำงาน · ไม่ต้องลงทุน", ja: "運用調整 · 投資不要", zh: "调整运行 · 无需投资" },
  "Shift loads, stand down idle machines, shave peaks — free, and AI can run it for you.": { th: "ย้ายโหลด · ปิดเครื่อง idle · ลดพีค — ฟรี และให้ AI จัดการอัตโนมัติได้", ja: "負荷シフト・アイドル停止・ピーク削減 — 無償、AIが自動実行可能。", zh: "转移负荷·停待机·削峰 — 免费，且AI可自动执行。" },
  "Do now": { th: "ทำได้เลย", ja: "今すぐ実施", zh: "立即可做" },
  "Invest to fix the root cause": { th: "ลงทุนแก้ที่ต้นเหตุ", ja: "根本原因に投資して解決", zh: "投资根治问题" },
  "Buy parts or service to fix it for good — needs budget approval and a work order.": { th: "ซื้ออะไหล่หรือ service เพื่อแก้ให้หายขาด — ต้องอนุมัติงบ + ออกใบสั่งงาน", ja: "部品・サービスで恒久対策 — 予算承認と作業指示が必要。", zh: "购件或服务以彻底解决 — 需预算审批与工单。" },
  "Peak demand manager": { th: "จัดการดีมานด์พีค", ja: "ピークデマンド管理", zh: "峰值需量管理" },
  "Peak Demand Autopilot": { th: "คุมดีมานด์พีคอัตโนมัติ", ja: "ピークデマンド・オートパイロット", zh: "峰值需量自动驾驶" },
  "Idle Machine Optimizer": { th: "จัดการเครื่องเดินเปล่า", ja: "アイドル機オプティマイザー", zh: "空转设备优化器" },
  "Off-Peak Load Shifter": { th: "ย้ายโหลดไปช่วงออฟพีค", ja: "オフピーク・ロードシフター", zh: "谷时负荷转移器" },
  "Sequential Start Scheduler": { th: "ทยอยสตาร์ทเครื่องตามคิว", ja: "順次起動スケジューラー", zh: "顺序启动调度器" },
  "Shift start": { th: "เริ่มกะ", ja: "シフト開始", zh: "换班开始" },
  "machines set to start together": { th: "เครื่องที่ตั้งไว้ให้เปิดพร้อมกัน", ja: "台が同時起動予定", zh: "台设备同时启动" },
  "Start together": { th: "เปิดพร้อมกัน", ja: "同時起動", zh: "同时启动" },
  "Staggered": { th: "ไล่ลำดับ", ja: "分散起動", zh: "错峰启动" },
  "Stagger interval": { th: "ระยะห่างการสตาร์ท", ja: "起動間隔", zh: "启动间隔" },
  "Start sequence · AI-ordered": { th: "ลำดับการสตาร์ท · AI จัดให้", ja: "起動順序 · AI最適化", zh: "启动顺序 · AI 排序" },
  "Not sequenced": { th: "ไม่จัดลำดับ", ja: "順序制御なし", zh: "不排序" },
  "Add machine": { th: "เพิ่มเครื่อง", ja: "機械を追加", zh: "添加设备" },
  "All machines added": { th: "เพิ่มครบทุกเครื่องแล้ว", ja: "全機械を追加済み", zh: "已添加全部设备" },
  "Remove": { th: "ลบ", ja: "削除", zh: "移除" },
  "Startup spike avoided": { th: "เลี่ยงโหลดพุ่งตอนสตาร์ทได้", ja: "起動スパイク回避量", zh: "避免的启动尖峰" },
  "Under cap": { th: "ใต้เพดาน", ja: "上限内", zh: "低于上限" },
  "Still over cap": { th: "ยังเกินเพดาน", ja: "まだ上限超過", zh: "仍超上限" },
  "AI sequences the starts via PLC automatically at shift change.": { th: "AI สั่ง PLC ไล่ลำดับสตาร์ทให้อัตโนมัติตอนเปลี่ยนกะ", ja: "シフト交代時、AIがPLC経由で起動を自動順序制御。", zh: "换班时 AI 自动通过 PLC 顺序启动。" },
  "Send start schedule to PLC": { th: "ส่งตารางสตาร์ทไป PLC", ja: "起動スケジュールをPLCへ送信", zh: "向 PLC 下发启动计划" },
  "Live Peak Shield": { th: "คุมพีคเรียลไทม์", ja: "ライブ・ピークシールド", zh: "实时削峰护盾" },
  "Detected Issues": { th: "ปัญหาที่ตรวจพบ", ja: "検出された問題", zh: "检测到的问题" },
  "Linked Work Orders": { th: "ใบสั่งงานที่เชื่อมโยง", ja: "紐付けされた作業指示", zh: "关联工单" },
  "Load-shift manager": { th: "จัดการ Load Shifting", ja: "負荷シフト管理", zh: "负荷转移管理" },
  "Idle-standby manager": { th: "จัดการปิดเครื่องที่ Idle", ja: "アイドル待機管理", zh: "空转待机管理" },
  "Auto": { th: "อัตโนมัติ", ja: "自動", zh: "自动" },
  "Demand target": { th: "เป้าหมายดีมานด์", ja: "デマンド目標", zh: "需量目标" },
  "Projected": { th: "คาดว่าจะเหลือ", ja: "予測", zh: "预计" },
  "Sheddable loads · by priority": { th: "โหลดที่ปลดได้ · ตามลำดับ", ja: "遮断可能な負荷 · 優先順", zh: "可切除负载 · 按优先级" },
  "Loads to cut · by priority": { th: "โหลดที่ลดได้ · ตามลำดับ", ja: "削減可能な負荷 · 優先順", zh: "可削减负载 · 按优先级" },
  "Can shut off": { th: "ปิดได้", ja: "停止可", zh: "可关闭" },
  "Dim only": { th: "หรี่ได้", ja: "抑制のみ", zh: "仅可调低" },
  "Setup needed": { th: "ต้องติดตั้งก่อน", ja: "設置が必要", zh: "需先安装" },
  "Requires": { th: "ต้องมี", ja: "要", zh: "需要" },
  "install in Level 2 first": { th: "ติดตั้งใน Level 2 ก่อน", ja: "先にレベル2で設置", zh: "先在 Level 2 安装" },
  "Cut off": { th: "ปลด", ja: "遮断", zh: "切除" },
  "Reduce by": { th: "ลดลง", ja: "削減量", zh: "降低" },
  "left": { th: "เหลือ", ja: "残", zh: "剩" },
  "Will trim": { th: "จะลด", ja: "削減量", zh: "将削减" },
  "After trim": { th: "หลังลด", ja: "削減後", zh: "削减后" },
  "AI commands the PLC/BMS to trim power automatically as the peak approaches.": { th: "AI สั่ง PLC/BMS ลดกำลังให้อัตโนมัติเมื่อพีคใกล้ชนเพดาน", ja: "ピーク接近時、AIがPLC/BMSに電力削減を自動指令します。", zh: "接近峰值时，AI自动指令PLC/BMS削减功率。" },
  "Manual — shows each action for your team to run (switch off / dim).": { th: "แมนนวล — แสดงคำสั่งให้ทีมดำเนินการเอง (ปิด / หรี่ ตามรา·าร)", ja: "手動 — 各操作(停止/抑制)をチームが実行できるよう表示。", zh: "手动 — 显示每项操作供团队执行(关闭/调低)。" },
  "Send command to PLC": { th: "สั่ง PLC ลดกำลัง", ja: "PLCへ指令を送信", zh: "向PLC下发指令" },
  "Command sent to PLC": { th: "ส่งคำสั่งไป PLC แล้ว", ja: "PLCへ指令送信済み", zh: "已向PLC下发指令" },
  "Send standby command to PLC": { th: "สั่ง PLC เข้าสแตนด์บาย", ja: "PLCへ待機指令を送信", zh: "向PLC下发待机指令" },
  "units": { th: "เครื่อง", ja: "台", zh: "台" },
  "AI commands the PLC/BMS to put idle machines on standby automatically.": { th: "AI สั่ง PLC/BMS ให้เครื่องที่ว่างเข้าสแตนด์บายอัตโนมัติ", ja: "AIがアイドル機をPLC/BMS経由で自動待機させます。", zh: "AI自动指令PLC/BMS让空转设备进入待机。" },
  "Will shed": { th: "จะปลด", ja: "遮断量", zh: "将切除" },
  "keeps peak under target": { th: "คุมพีคใต้เป้าหมายได้", ja: "ピークを目標以下に維持", zh: "可将峰值控制在目标以下" },
  "still over target": { th: "ยังเกินเป้าหมาย", ja: "まだ目標超過", zh: "仍超出目标" },
  "save": { th: "ประหยัด", ja: "削減", zh: "节省" },
  "After shed": { th: "หลังปลด", ja: "遮断後", zh: "切除后" },
  "Let AI handle it": { th: "ให้ AI จัดการเอง", ja: "AIに任せる", zh: "交给 AI 处理" },
  "Peak will stay under target": { th: "พีคจะอยู่ใต้เป้าหมาย", ja: "ピークは目標以下に収まる", zh: "峰值将保持在目标以下" },
  "Peak will breach target — shed more": { th: "พีคจะเกินเป้า — ปลดโหลดเพิ่ม", ja: "ピークが目標超過 — さらに遮断を", zh: "峰值将超标 — 需增加切除" },
  "machines can go to standby now": { th: "เครื่องพร้อมเข้าสแตนด์บา·ันที", ja: "台が今すぐ待機可能", zh: "台设备可立即待机" },
  "No machines over the limit yet": { th: "ยังไม่มีเครื่องถึงเกณฑ์", ja: "しきい値超過の機械なし", zh: "暂无设备超过阈值" },
  "loads ready to shift to off-peak": { th: "โหลดพร้อมเลื่อนไปช่วงออฟพีค", ja: "件の負荷がオフピークへ移行可能", zh: "项负载可转移至谷时" },
  "Move": { th: "เลื่อน", ja: "移行", zh: "转移" },
  "Call it idle after": { th: "ถือว่า Idle เมื่อเดินตัวเปล่าเกิน", ja: "アイドル判定時間", zh: "空转超过此时长视为闲置" },
  "Idle Condition": { th: "เงื่อนไข Idle", ja: "アイドル条件", zh: "空转条件" },
  "minutes": { th: "นาที", ja: "分", zh: "分钟" },
  "idle for": { th: "เดินตัวเปล่ามาแล้ว", ja: "アイドル時間", zh: "已空转" },
  "qualifies": { th: "เข้าเกณฑ์", ja: "対象", zh: "符合" },
  "not yet": { th: "ยังไม่ถึงเกณฑ์", ja: "未達", zh: "未达标" },
  "machines qualify": { th: "เครื่องเข้าเกณฑ์", ja: "台が対象", zh: "台设备符合" },
  "Off-peak window": { th: "ช่วงออฟพีค", ja: "オフピーク時間帯", zh: "谷时时段" },
  "Shifted to off-peak": { th: "ย้ายไปช่วงออฟพีค", ja: "オフピークへ移行", zh: "已转移至谷时" },
  "Est. saving": { th: "ประหยัดโดยประมาณ", ja: "推定削減", zh: "预计节省" },
  "Manage in AI Optimization": { th: "จัดการใน AI Optimization", ja: "AI最適化で管理", zh: "在 AI 优化中管理" },
  "Go to controls": { th: "ไปที่เครื่องมือจัดการ", ja: "管理ツールへ", zh: "前往管理工具" },
  /* findings view toggle + compact card */
  "Detailed": { th: "ละเอียด", ja: "詳細", zh: "详细" },
  "Compact": { th: "กระชับ", ja: "コンパクト", zh: "简洁" },
  "Problem detected": { th: "ปัญหาที่ตรวจพบ", ja: "検出された問題", zh: "检测到的问题" },
  "AI analysis": { th: "AI วิเคราะห์", ja: "AI分析", zh: "AI 分析" },
  "Recommended action": { th: "สิ่งที่ควรทำ", ja: "推奨アクション", zh: "建议措施" },
  "Recommended part spec": { th: "สเปกอุปกรณ์ที่แนะนำ", ja: "推奨部品仕様", zh: "建议部件规格" },
  "Est. savings": { th: "ประหยัดโดยประมาณ", ja: "推定削減額", zh: "预计节省" },
  "Execute": { th: "ดำเนินการเลย", ja: "実行", zh: "立即执行" },
  /* settings — machine criticality */
  "Machine criticality": { th: "การจัดประเภทเครื่องจักร", ja: "機器の重要度", zh: "机器关键性" },
  "Classify machines · Critical are protected from AI auto-management": { th: "จัดประเภทเครื่องจักร · เครื่อง Critical จะถูกปกป้องจากการจัดการอัตโนมัติของ AI", ja: "機器を分類 · CriticalはAIの自動管理から保護", zh: "对机器分类 · Critical 受保护，不被 AI 自动管理" },
  "Critical machines": { th: "เครื่อง Critical", ja: "Critical機器", zh: "关键机器" },
  "Non-Critical machines": { th: "เครื่อง Non-Critical", ja: "Non-Critical機器", zh: "非关键机器" },
  "Protected — AI never auto-sheds or standbys this machine": { th: "ถูกปกป้อง — AI จะไม่ปลดโหลด/พักเครื่องนี้อัตโนมัติ", ja: "保護 — AIは自動遮断/待機しません", zh: "受保护 — AI 不会自动切除/待机" },
  "Auto-manageable — AI may shed or standby this machine": { th: "จัดการอัตโนมัติได้ — AI อาจปลดโหลด/พักเครื่องนี้", ja: "自動管理可 — AIが遮断/待機する場合あり", zh: "可自动管理 — AI 可切除/待机" },
  "Set all production as Critical": { th: "ตั้งเครื่องผลิตทั้งหมดเป็น Critical", ja: "全生産機器をCriticalに", zh: "将所有生产机器设为关键" },
  "This classification feeds the AI Optimization guardrails.": { th: "การจัดประเภทนี้เชื่อมกับ guardrail ใน AI Optimization", ja: "この分類はAI最適化のガードレールに反映されます。", zh: "此分类将用于 AI 优化的护栏。" },
  "Search machines…": { th: "ค้นหาเครื่องจักร…", ja: "機器を検索…", zh: "搜索机器…" },
  "Machine name": { th: "เครื่องจักร", ja: "機器名", zh: "机器" },
  "Machine category": { th: "หมวด", ja: "区分", zh: "类别" },
  "Health status": { th: "สถานะ", ja: "状態", zh: "状态" },
  "Criticality": { th: "การจัดประเภท", ja: "重要度", zh: "关键性" },
  "Asset ID": { th: "Asset ID", ja: "資産ID", zh: "资产 ID" },
  /* settings — sections */
  "Machines & assets": { th: "เครื่องจักร & สินทรัพย์", ja: "機器・資産", zh: "机器与资产" },
  "Tariff & billing": { th: "ค่าไฟ & การเรี·เก็บ", ja: "料金・請求", zh: "电价与账单" },
  "AI & automation": { th: "AI & ระบบอัตโนมัติ", ja: "AI・自動化", zh: "AI 与自动化" },
  "Notifications": { th: "การแจ้งเตือน", ja: "通知", zh: "通知" },
  "Users & roles": { th: "ผู้ใช้ & สิทธิ์", ja: "ユーザー・権限", zh: "用户与权限" },
  /* settings — tariff */
  "Electricity tariff": { th: "อัตราค่าไฟฟ้า", ja: "電気料金", zh: "电价" },
  "These rates power Peak & Cost and the Tariff Optimizer.": { th: "อัตราเหล่านี้ป้อนให้ Peak & Cost และ Tariff Optimizer", ja: "これらの料金はPeak & CostとTariff Optimizerに反映されます。", zh: "这些电价用于 Peak & Cost 与电价优化。" },
  "Save changes": { th: "บันทึก", ja: "変更を保存", zh: "保存更改" },
  "Saved": { th: "บันทึกแล้ว", ja: "保存済み", zh: "已保存" },
  "Utility provider": { th: "การไฟฟ้า", ja: "電力会社", zh: "供电方" },
  "Tariff type": { th: "ประเภทอัตรา", ja: "料金タイプ", zh: "电价类型" },
  "Normal": { th: "แบบปกติ", ja: "通常", zh: "普通" },
  "Billing cycle day": { th: "วันตัดรอบบิล", ja: "請求締日", zh: "账单结算日" },
  "of month": { th: "ของเดือน", ja: "日", zh: "日" },
  "On-peak window": { th: "ช่วง on-peak", ja: "オンピーク時間帯", zh: "峰时时段" },
  "Demand contract": { th: "สัญญาดีมานด์", ja: "契約電力", zh: "合约需量" },
  "Demand charge": { th: "ค่าดีมานด์", ja: "デマンド料金", zh: "需量电费" },
  "PF penalty below": { th: "โดนค่าปรับ PF เมื่อต่ำกว่า", ja: "力率ペナルティ (未満)", zh: "功率因数罚款低于" },
  "Changing these updates every saving, payback and bill figure across the app.": { th: "แก้ค่าเหล่านี้จะอัปเดตตัวเลขประหยัด/คืนทุน/บิลทั้งแอป", ja: "変更するとアプリ全体の削減・回収・請求額が更新されます。", zh: "更改后将更新全应用的节省、回收与账单数字。" },
  /* settings — automation */
  "How much the AI is allowed to do on its own — applies to all managers.": { th: "AI ทำเองได้แค่ไหน — มีผลกับทุกเครื่องมือจัดการ", ja: "AIが自律的に行える範囲 — 全マネージャーに適用", zh: "AI 可自主执行的范围 — 适用于所有管理器" },
  "Hard limits the AI can never cross.": { th: "ขอบเขตที่ AI ห้ามข้ามเด็ดขาด", ja: "AIが決して超えられない制限", zh: "AI 绝不可逾越的硬性限制" },
  "Never shed machines marked Critical": { th: "ห้ามปลดเครื่องที่ตั้งเป็น Critical", ja: "Critical指定の機器は遮断しない", zh: "绝不切除标记为关键的机器" },
  "Hold process temperature within": { th: "คุมอุณหภูมิกระบวนการภายใน", ja: "プロセス温度を維持", zh: "工艺温度维持在" },
  "Keep power factor between": { th: "คุมเพาเวอร์แฟกเตอร์ระหว่าง", ja: "力率を維持", zh: "功率因数保持在" },
  "Every action is logged & reversible": { th: "ทุกการทำงานถูกบันทึกและย้อนกลับได้", ja: "全操作は記録され取り消し可能", zh: "每项操作均记录且可回退" },
  "Manager defaults": { th: "ค่าเริ่มต้นของเครื่องมือจัดการ", ja: "マネージャー既定値", zh: "管理器默认值" },
  "Starting values for the Peak, Idle and Load-shift managers.": { th: "ค่าเริ่มต้นของ Peak / Idle / Load-shift manager", ja: "Peak/Idle/Load-shiftマネージャーの初期値", zh: "Peak / Idle / Load-shift 管理器的初始值" },
  "Idle threshold": { th: "เกณฑ์ Idle", ja: "アイドルしきい値", zh: "空转阈值" },
  "min": { th: "นาที", ja: "分", zh: "分钟" },
  "Peak demand target": { th: "เป้าดีมานด์พีค", ja: "ピークデマンド目標", zh: "峰值需量目标" },
  /* settings — notifications */
  "Notification channels": { th: "ช่องทางแจ้งเตือน", ja: "通知チャネル", zh: "通知渠道" },
  "Where alerts are delivered.": { th: "ส่งการแจ้งเตือนไปที่ไหน", ja: "アラートの配信先", zh: "警报发送到哪里" },
  "Browser push": { th: "แจ้งเตือนผ่านเบราว์เซอร์", ja: "ブラウザ通知", zh: "浏览器推送" },
  "Alert me about": { th: "แจ้งเตือนเรื่อง", ja: "通知する項目", zh: "提醒我关于" },
  "Which events trigger a notification.": { th: "เหตุการณ์ไหนที่จะแจ้งเตือน", ja: "どのイベントで通知するか", zh: "哪些事件触发通知" },
  "Peak demand breach": { th: "ดีมานด์เกินสัญญา", ja: "デマンド超過", zh: "需量超限" },
  "Power-quality events (sag/swell)": { th: "เหตุการณ์คุณภาพไฟ (ไฟตก/เกิน)", ja: "電力品質イベント (サグ/スウェル)", zh: "电能质量事件 (暂降/暂升)" },
  "Energy anomalies": { th: "ความผิดปกติด้านพลังงาน", ja: "エネルギー異常", zh: "能耗异常" },
  "Equipment failure risk": { th: "ความเสี่ยงเครื่องจักรเสีย", ja: "設備故障リスク", zh: "设备故障风险" },
  "Quiet hours": { th: "ช่วงเงียบ", ja: "サイレント時間", zh: "免打扰时段" },
  "Hold non-critical alerts during these hours.": { th: "งดแจ้งเตือนที่ไม่วิกฤตในช่วงนี้", ja: "この時間帯は重要でない通知を保留", zh: "此时段暂停非关键提醒" },
  "Critical alerts always go through.": { th: "การเตือนวิกฤตส่งเสมอ", ja: "重大アラートは常に送信されます。", zh: "关键警报始终发送。" },
  /* settings — users */
  "Team & access": { th: "ทีม & สิทธิ์เข้าถึง", ja: "チーム・アクセス", zh: "团队与访问" },
  "Who can view, approve and execute in this plant.": { th: "ใครดู/อนุมัติ/สั่งดำเนินการในโรงงานนี้ได้", ja: "この工場で閲覧・承認・実行できる人", zh: "谁能在本厂查看、批准与执行" },
  "Invite user": { th: "เชิญผู้ใช้", ja: "ユーザーを招待", zh: "邀请用户" },
  "User": { th: "ผู้ใช้", ja: "ユーザー", zh: "用户" },
  "Role": { th: "บทบาท", ja: "役割", zh: "角色" },
  "Active": { th: "ใช้งานอยู่", ja: "有効", zh: "已激活" },
  "Invited": { th: "เชิญแล้ว", ja: "招待済み", zh: "已邀请" },
  "What each role can do": { th: "แต่ละบทบาททำอะไรได้", ja: "各役割の権限", zh: "各角色权限" },
  "Recent activity · audit trail": { th: "กิจกรรมล่าสุด · บันทึกการตรวจสอบ", ja: "最近のアクティビティ · 監査証跡", zh: "近期活动 · 审计追踪" },
  "Manage": { th: "จัดการ", ja: "管理", zh: "管理" },
  /* tariff & demand-contract optimizer */
  "Tariff & contract optimizer": { th: "จูนค่าไฟ & สัญญาดีมานด์", ja: "料金・契約最適化", zh: "电价与合约优化" },
  "No capex": { th: "ไม่ต้องลงทุน", ja: "投資不要", zh: "无需投资" },
  "Right-size your demand contract → save": { th: "ปรับขนาดสัญญาดีมานด์ให้พอดี → ประหยัด", ja: "契約電力を適正化 → 削減", zh: "合约需量适配 → 节省" },
  "You pay demand at": { th: "คุณจ่ายค่าดีมานด์ที่", ja: "契約電力", zh: "您按此合约需量付费" },
  "but your real 12-month peak is only": { th: "แต่พีคจริง 12 เดือนสูงสุดแค่", ja: "しかし直近12ヶ月の実ピークは", zh: "但12个月实际峰值仅" },
  "Set contract to": { th: "ตั้งสัญญาเป็น", ja: "契約値", zh: "设置合约为" },
  "safe — headroom": { th: "ปลอดภัย · เหลือ headroom", ja: "安全 · 余裕", zh: "安全 · 余量" },
  "above real peak": { th: "เหนือพีคจริง", ja: "実ピーク超", zh: "高于实际峰值" },
  "risk — below real peak, penalties likely": { th: "เสี่ยง · ต่ำกว่าพีคจริง อาจโดนค่าปรับ", ja: "リスク · 実ピーク未満、ペナルティの恐れ", zh: "有风险 · 低于实际峰值，可能被罚" },
  "Current contract": { th: "สัญญาปัจจุบัน", ja: "現在の契約", zh: "当前合约" },
  "Real 12-month peak": { th: "พีคจริงสูงสุด 12 เดือน", ja: "12ヶ月実ピーク", zh: "12个月实际峰值" },
  "Recommended": { th: "แนะนำ", ja: "推奨", zh: "建议" },
  "You're on": { th: "คุณอยู่บนอัตรา", ja: "現在の料金", zh: "您当前电价" },
  "on-peak — shift more load off-peak to cut the on-peak bill.": { th: "on-peak — ย้ายโหลดไป off-peak เพิ่มเพื่อลดค่าไฟช่วง on-peak", ja: "オンピーク — 負荷を更にオフピークへ移しオンピーク料金を削減", zh: "峰时 — 将更多负荷转移至谷时以降低峰时电费" },
  "Open Load-shift manager": { th: "เปิดตัวจัดการ Load Shifting", ja: "負荷シフト管理を開く", zh: "打开负荷转移管理" },
  "Billed peak · last 12 months": { th: "พีคที่ถูกคิดเงิน · 12 เดือนล่าสุด", ja: "課金ピーク · 直近12ヶ月", zh: "计费峰值 · 近12个月" },
  "New target": { th: "เป้าใหม่", ja: "新目標", zh: "新目标" },
  "Gap between the red contract line and the bars = what you overpay every month.": { th: "ช่องว่างระหว่างเส้นสัญญา (แดง) กับแท่ง = ส่วนที่จ่ายเกินทุกเดือน", ja: "赤い契約線と棒の差 = 毎月の過払い分", zh: "红色合约线与柱状图之间的差 = 每月多付的部分" },
  /* ------------------------------------------------------------ Report tab */
  "Report": { th: "รายงาน", ja: "レポート", zh: "报告" },
  "Generate a report": { th: "ออกรายงาน", ja: "レポートを作成", zh: "生成报告" },
  "every report opens with a 1-page AI executive summary": { th: "ทุกฉบับขึ้นต้นด้วยบทสรุปผู้บริหารที่ AI เขียนให้ 1 หน้า", ja: "全レポートはAIによる1ページの要約から始まります", zh: "每份报告均以AI撰写的1页摘要开头" },
  "For": { th: "สำหรับ", ja: "対象", zh: "对象" },
  "Data period": { th: "ช่วงข้อมูล", ja: "データ期間", zh: "数据期间" },
  "Format · language": { th: "รูปแบบ · ภาษา", ja: "形式 · 言語", zh: "格式 · 语言" },
  "Auto-send": { th: "ส่งอัตโนมัติ", ja: "自動送信", zh: "自动发送" },
  "end of day": { th: "ทุกท้ายวัน", ja: "毎日終業時", zh: "每日结束时" },
  "end of week": { th: "ทุกท้ายสัปดาห์", ja: "毎週末", zh: "每周末" },
  "end of month": { th: "ทุกสิ้นเดือน", ja: "毎月末", zh: "每月末" },
  "today": { th: "วันนี้", ja: "今日", zh: "今天" },
  "last 7 days": { th: "7 วันล่าสุด", ja: "過去7日間", zh: "近7天" },
  "this month": { th: "เดือนนี้", ja: "今月", zh: "本月" },
  "Operations": { th: "ปฏิบัติการ", ja: "オペレーション", zh: "运营" },
  "Engineering": { th: "วิศวกรรม", ja: "エンジニアリング", zh: "工程" },
  "Executive": { th: "ผู้บริหาร", ja: "経営層", zh: "管理层" },
  "Auto-delivery goes out over Email/LINE on the chosen cadence · every figure in these reports comes from the same power meters the Live tabs read": { th: "การส่งอัตโนมัติจะเข้า Email/LINE ตามรอบที่เลือก · ตัวเลขทุกตัวมาจากมิเตอร์ไฟฟ้าชุดเดียวกับที่แท็บ Live อ่าน", ja: "自動配信は選択した周期でEmail/LINEに送信 · 全数値はLiveタブと同じ電力メーターから", zh: "自动发送按所选周期通过Email/LINE送达 · 所有数据均来自Live页签所读的同一批电表" },
  "Daily energy report": { th: "รายงานพลังงานประจำวัน", ja: "日次エネルギーレポート", zh: "每日能源报告" },
  "kWh, baht and peak vs baseline — with a 1-paragraph AI summary": { th: "หน่วยไฟ ค่าไฟ และพีค เทียบ baseline พร้อมสรุปโดย AI 1 ย่อหน้า", ja: "kWh・料金・ピークをベースライン比較、AI要約付き", zh: "kWh、电费与峰值对比基线，附AI摘要" },
  "plant manager · shift leads": { th: "ผจก.โรงงาน · หัวหน้ากะ", ja: "工場長 · シフト長", zh: "厂长 · 班组长" },
  "Power quality report": { th: "รายงานคุณภาพไฟฟ้า", ja: "電力品質レポート", zh: "电能质量报告" },
  "PF, THD, unbalance and disturbance events vs IEEE/EN limits": { th: "PF, THD, ความไม่สมดุล และเหตุการณ์ผิดปกติ เทียบเกณฑ์ IEEE/EN", ja: "PF・THD・不平衡・外乱イベントをIEEE/EN基準と比較", zh: "PF、THD、不平衡与扰动事件对照IEEE/EN限值" },
  "electrical engineer": { th: "วิศวกรไฟฟ้า", ja: "電気エンジニア", zh: "电气工程师" },
  "Load & peak analysis": { th: "รายงานโหลดและพีค", ja: "負荷・ピーク分析", zh: "负荷与峰值分析" },
  "24-h load shape, peak window and demand-charge exposure": { th: "โปรไฟล์โหลด 24 ชม. หน้าต่างพีค และความเสี่ยงค่าดีมานด์", ja: "24時間負荷形状・ピーク時間帯・デマンド料金リスク", zh: "24小时负荷曲线、峰值时段与需量电费风险" },
  "Machine energy report": { th: "รายงานพลังงานรายเครื่อง", ja: "設備別エネルギーレポート", zh: "设备能耗报告" },
  "top consumers and abnormal draw, traced to the machine": { th: "เครื่องที่กินไฟสูงสุด และการใช้ไฟผิดปกติ โยงถึงตัวเครื่อง", ja: "大口消費設備と異常消費を設備単位で追跡", zh: "高耗能设备与异常用电，追溯到具体设备" },
  "engineers · maintenance": { th: "วิศวกร · ซ่อมบำรุง", ja: "エンジニア · 保全", zh: "工程师 · 维护" },
  "Cost & tariff report": { th: "รายงานค่าไฟและอัตรา TOU", ja: "コスト・料金レポート", zh: "电费与费率报告" },
  "TOU breakdown, demand charge and penalty risk": { th: "แ·ค่าไฟตาม TOU ค่าดีมานด์ และความเสี่ยงค่าปรับ", ja: "TOU内訳・デマンド料金・ペナルティリスク", zh: "TOU分解、需量电费与罚款风险" },
  "executives · finance": { th: "ผู้บริหาร · การเงิน", ja: "経営層 · 財務", zh: "管理层 · 财务" },
  "Savings verification": { th: "รายงานยืนยันผลประหยัด", ja: "省エネ実績検証", zh: "节能核证报告" },
  "measure-by-measure baht saved, verified against the baseline": { th: "เงินที่ประหยัดได้รายมาตรการ พิสูจน์เทียบ baseline จริง", ja: "施策別の削減額をベースラインで検証", zh: "逐项措施节省金额，对照基线核证" },
  "executives": { th: "ผู้บริหาร", ja: "経営層", zh: "管理层" },
  "Executive summary · by AI": { th: "บทสรุปผู้บริหาร · โดย AI", ja: "エグゼクティブサマリー · AI作成", zh: "管理层摘要 · AI撰写" },
  "Bangkok Plant 1": { th: "โรงงานกรุงเทพ 1", ja: "バンコク第1工場", zh: "曼谷1厂" },
  "Meter verified": { th: "ยืนยันจากมิเตอร์", ja: "メーター検証済", zh: "电表核证" },
  "live data": { th: "ข้อมูลจริง", ja: "ライブデータ", zh: "实时数据" },
  "Source": { th: "แหล่งข้อมูล", ja: "データ源", zh: "数据来源" },
  "Incomer + MDB meters": { th: "มิเตอร์จุดรับไฟ + ตู้ MDB", ja: "引込＋MDBメーター", zh: "进线+MDB电表" },
  "Prepared by": { th: "ผู้จัดทำ", ja: "作成者", zh: "编制人" },
  "EnergyAI · automatic": { th: "EnergyAI · อัตโนมัติ", ja: "EnergyAI · 自動", zh: "EnergyAI · 自动" },
  "all shifts": { th: "ทุกกะ", ja: "全シフト", zh: "全部班次" },
  "page": { th: "หน้า", ja: "ページ", zh: "页" },
  "internal use": { th: "ใช้ภายใน", ja: "社内用", zh: "内部使用" },
  "Download PDF": { th: "ดาวน์โหลด PDF", ja: "PDFをダウンロード", zh: "下载PDF" },
  "generating…": { th: "กำลังสร้าง…", ja: "生成中…", zh: "生成中…" },
  "downloaded": { th: "ดาวน์โหลดแล้ว", ja: "ダウンロード済", zh: "已下载" },
  "close": { th: "ปิด", ja: "閉じる", zh: "关闭" },
  "PDF · print-sharp": { th: "PDF · คมชัดระดับพิมพ์", ja: "PDF · 印刷品質", zh: "PDF · 印刷级清晰" },
  "Prepared · EnergyAI (auto)": { th: "ผู้จัดทำ · EnergyAI (อัตโนมัติ)", ja: "作成 · EnergyAI（自動）", zh: "编制 · EnergyAI（自动）" },
  "Reviewed · Electrical engineer": { th: "ผู้ตรวจ · วิศวกรไฟฟ้า", ja: "確認 · 電気エンジニア", zh: "审核 · 电气工程师" },
  "Approved · Plant manager": { th: "ผู้อนุมัติ · ผู้จัดการโรงงาน", ja: "承認 · 工場長", zh: "批准 · 厂长" },
  "Generated by SpareX FactoryOS™ · EnergyAI — every figure comes from the incomer and MDB power meters": { th: "สร้างโดย SpareX FactoryOS™ · EnergyAI — ตัวเลขทุกตัวมาจากมิเตอร์จุดรับไฟและตู้ MDB", ja: "SpareX FactoryOS™ · EnergyAI作成 — 全数値は引込・MDBメーターより", zh: "由SpareX FactoryOS™ · EnergyAI生成 — 所有数据来自进线与MDB电表" },
  "Today's key numbers": { th: "ตัวเลขหลักวันนี้", ja: "本日の主要数値", zh: "今日关键数据" },
  "Energy today": { th: "ใช้ไฟวันนี้", ja: "本日の使用電力量", zh: "今日用电" },
  "vs baseline": { th: "เทียบ baseline", ja: "ベースライン比", zh: "对比基线" },
  "Cost today": { th: "ค่าไฟวันนี้", ja: "本日のコスト", zh: "今日电费" },
  "blended tariff": { th: "อัตราเฉลี่ยถ่วงน้ำหนัก", ja: "平均単価", zh: "综合电价" },
  "Peak today": { th: "พีควันนี้", ja: "本日のピーク", zh: "今日峰值" },
  "contract": { th: "สัญญา", ja: "契約", zh: "合约" },
  "AI saved · MTD": { th: "AI ประหยัดให้ · เดือนนี้", ja: "AI削減額 · 今月", zh: "AI节省 · 本月" },
  "verified by meters": { th: "ยืนยันจากมิเตอร์จริง", ja: "メーターで検証済", zh: "经电表核证" },
  "Top consumers · today": { th: "เครื่องที่กินไฟสูงสุด · วันนี้", ja: "大口消費設備 · 本日", zh: "高耗能设备 · 今日" },
  "Machine": { th: "เครื่อง", ja: "設備", zh: "设备" },
  "day": { th: "วัน", ja: "日", zh: "天" },
  "month": { th: "เดือน", ja: "月", zh: "月" },
  "What to do next · ranked by AI": { th: "สิ่งที่ควรทำต่อ · เรียงโดย AI", ja: "次のアクション · AI優先順", zh: "后续行动 · AI排序" },
  "Raise the Chiller B work order — condenser fouling is burning baht every hour and fails in ~3 days": { th: "ออกใบสั่งงาน Chiller B — คอนเดนเซอร์ตันกำลังเผาเงินทุกชั่วโมง และจะพังในอีก ~3 วัน", ja: "Chiller Bの作業指示を発行 — 凝縮器汚れで毎時損失、約3日で故障見込み", zh: "下达Chiller B工单 — 冷凝器结垢每小时都在烧钱，约3天后故障" },
  "Today's energy is running ~12% above the 30-day baseline: the on-peak window overlapped with simultaneous chiller and compressor load, and Chiller B is drawing +15% from condenser fouling. Consumption today is ≈ 31,760 kWh (≈ ฿111K). AI actions have already saved ฿212K this month. Fix Chiller B and keep the pre-cool schedule to bring tomorrow back to baseline.": { th: "การใช้ไฟวันนี้สูงกว่า baseline 30 วันราว 12%: ช่วง on-peak ชนกับโหลด Chiller และ Compressor ที่เดินพร้อมกัน และ Chiller B กินไฟเกิน +15% จากคอนเดนเซอร์ตัน วันนี้ใช้ ≈ 31,760 kWh (≈ ฿111K) มาตรการ AI ประหยัดให้แล้ว ฿212K ในเดือนนี้ — ซ่อม Chiller B และคงตาราง pre-cool เพื่อดึงพรุ่งนี้กลับสู่ baseline", ja: "本日の使用電力は30日ベースライン比約+12%。オンピークにチラーとコンプレッサーの同時負荷が重なり、Chiller Bは凝縮器汚れで+15%。本日≈31,760kWh（≈11.1万฿）。AI施策で今月既に21.2万฿削減。Chiller B修理とプレクール継続で明日はベースラインへ。", zh: "今日用电高于30天基线约12%：峰时段与冷机、空压机同时负荷重叠，Chiller B因冷凝器结垢多耗15%。今日≈31,760 kWh（≈฿111K）。AI措施本月已节省฿212K。修复Chiller B并保持预冷计划，明日即可回到基线。" },
  "Power quality KPIs": { th: "ตัวชี้วัดคุณภาพไฟฟ้า", ja: "電力品質KPI", zh: "电能质量KPI" },
  "weighted health index": { th: "ดัชนีสุขภาพถ่วงน้ำหนัก", ja: "加重健全度指数", zh: "加权健康指数" },
  "true PF at the incomer": { th: "PF จริงที่จุดรับไฟ", ja: "引込点の真の力率", zh: "进线真实功率因数" },
  "Standard": { th: "มาต°าน", ja: "規格", zh: "标准" },
  "Metric": { th: "ค่าที่วัด", ja: "指標", zh: "指标" },
  "pass": { th: "ผ่าน", ja: "適合", zh: "合格" },
  "watch": { th: "เฝ้าระวัง", ja: "要注視", zh: "关注" },
  "Disturbance events · cause and fix": { th: "เหตุการณ์ไฟผิดปกติ · สาเหตุและวิธีแก้", ja: "外乱イベント · 原因と対策", zh: "扰动事件 · 原因与对策" },
  "When": { th: "เมื่อไหร่", ja: "日時", zh: "时间" },
  "Event": { th: "เหตุการณ์", ja: "イベント", zh: "事件" },
  "Cause": { th: "สาเหตุ", ja: "原因", zh: "原因" },
  "Recommended fix": { th: "วิธีแก้ที่แนะนำ", ja: "推奨対策", zh: "建议措施" },
  "Power quality is healthy overall (PQ score 94/100) and inside IEEE-519 limits — voltage THD 3.0% of a 5% limit, current THD 6.4% of 8%. The one item that needs action: last night's sag on L2 came from Chiller B's direct-on-line motor start and violated the ITIC curve — PLCs risk resetting mid-run. A soft-starter on Chiller B removes the root cause.": { th: "คุณภาพไฟฟ้าโดยรวมอยู่ในเกณฑ์ดี (PQ 94/100) และไม่เกินเกณฑ์ IEEE-519 — THD แรงดัน 3.0% จากเกณฑ์ 5% กระแส 6.4% จาก 8% เรื่องเดียวที่ต้องจัดการ: ไฟตกที่เฟส L2 เมื่อคืนมาจากการสตาร์ทมอเตอร์ Chiller B แบบ DOL และหลุดเส้น ITIC — เสี่ยง PLC รีเซ็ตกลางไลน์ ติด soft-starter ที่ Chiller B คือการแก้ที่ต้นตอ", ja: "電力品質は全体的に健全（PQ 94/100）でIEEE-519基準内 — 電圧THD 3.0%/5%、電流THD 6.4%/8%。要対応は1件のみ：昨夜のL2サグはChiller BのDOL始動が原因でITIC曲線違反 — PLCリセットのリスク。ソフトスターター設置で根本解決。", zh: "电能质量整体健康（PQ 94/100），符合IEEE-519 — 电压THD 3.0%/5%，电流THD 6.4%/8%。唯一需处理：昨夜L2暂降源于Chiller B直接启动，违反ITIC曲线 — PLC有复位风险。加装软启动器即可根治。" },
  "Peak & demand KPIs": { th: "ตัวชี้วัดพีคและดีมานด์", ja: "ピーク・デマンドKPI", zh: "峰值与需量KPI" },
  "Monthly peak": { th: "พีคเดือนนี้", ja: "今月ピーク", zh: "本月峰值" },
  "Jun 24 · 13:42 · breach": { th: "24 มิ.ย. · 13:42 · เกินสัญญา", ja: "6/24 · 13:42 · 契約超過", zh: "6月24日 · 13:42 · 超约" },
  "Contract demand": { th: "ดีมานด์ตามสัญญา", ja: "契約デマンド", zh: "合约需量" },
  "demand charge": { th: "ค่าดีมานด์", ja: "デマンド料金", zh: "需量电费" },
  "Peak window": { th: "หน้าต่างพีค", ja: "ピーク時間帯", zh: "峰值时段" },
  "of breach risk": { th: "ของความเสี่ยงเกินสัญญา", ja: "の超過リスク", zh: "的超约风险" },
  "Penalty MTD": { th: "ค่าปรับเดือนนี้", ja: "今月ペナルティ", zh: "本月罚款" },
  "one breach event": { th: "เกินสัญญา 1 ครั้ง", ja: "超過1回", zh: "超约1次" },
  "Demand actions · ranked by AI": { th: "มาตรการลดพีค · เรียงโดย AI", ja: "デマンド対策 · AI優先順", zh: "需量措施 · AI排序" },
  "Action": { th: "มาตรการ", ja: "アクション", zh: "措施" },
  "Peak impact": { th: "ผลต่อพีค", ja: "ピーク効果", zh: "峰值影响" },
  "Mode": { th: "โหมด", ja: "モード", zh: "模式" },
  "automatic": { th: "อัตโนมัติ", ja: "自動", zh: "自动" },
  "needs approval": { th: "รออนุมัติ", ja: "要承認", zh: "需审批" },
  "Contract recommendation": { th: "ข้อเสนอเรื่องสัญญา", ja: "契約に関する提言", zh: "合约建议" },
  "Hold the shaved peak for 3 straight months, then right-size the demand contract 3,000 → 2,900 kW — a no-capex saving of ~฿13K every month": { th: "คุมพีคที่กดลงแล้วให้นิ่ง 3 เดือนติด แล้วปรับสัญญาดีมานด์ 3,000 → 2,900 kW — ประหยัด ~฿13K ทุกเดือนโดยไม่ต้องลงทุน", ja: "抑制後のピークを3ヶ月維持し、契約デマンドを3,000→2,900kWへ適正化 — 投資ゼロで毎月約1.3万฿削減", zh: "将削减后的峰值稳定3个月，再将合约需量从3,000调至2,900 kW — 零投资每月节省约฿13K" },
  "This month's peak hit 3,150 kW on Jun 24 at 13:42 — breaching the 3,000 kW contract and adding a ฿29,909 penalty to the bill. 78% of peak risk sits inside the 13:00–15:00 window. The four demand actions below trim ~345 kW of coincident load; once the shaved peak holds, the contract itself can be right-sized to 2,900 kW.": { th: "พีคเดือนนี้แตะ 3,150 kW เมื่อ 24 มิ.ย. เวลา 13:42 — เกินสัญญา 3,000 kW และเพิ่มค่าปรับ ฿29,909 เข้าบิล ความเสี่ยงพีค 78% อยู่ในช่วง 13:00–15:00 มาตรการ 4 ข้อด้านล่างตัดโหลดพร้อมกันได้ ~345 kW และเมื่อพีคใหม่นิ่งแล้ว ปรับสัญญาลงเหลือ 2,900 kW ได้อีกขั้น", ja: "今月ピークは6/24 13:42に3,150kWで契約3,000kW超過、ペナルティ29,909฿発生。リスクの78%は13–15時。下記4施策で同時負荷を約345kW削減、ピーク安定後は契約を2,900kWへ適正化可能。", zh: "本月峰值6月24日13:42达3,150 kW，超出3,000 kW合约并产生฿29,909罚款。78%的风险集中在13:00–15:00。以下4项措施可削减约345 kW同时负荷；峰值稳定后，合约可调整至2,900 kW。" },
  "Plant load KPIs": { th: "ตัวชี้วัดโหลดโรงงาน", ja: "工場負荷KPI", zh: "工厂负荷KPI" },
  "Live load": { th: "โหลดตอนนี้", ja: "現在負荷", zh: "当前负荷" },
  "all metered areas": { th: "ทุกโซนที่ติดมิเตอร์", ja: "全計測エリア", zh: "所有装表区域" },
  "Energy / day": { th: "พลังงาน / วัน", ja: "電力量 / 日", zh: "能耗 / 天" },
  "Metered machines": { th: "เครื่องที่ติดมิเตอร์", ja: "計測設備数", zh: "装表设备" },
  "via MDB submeters": { th: "ผ่านมิเตอร์ย่อยตู้ MDB", ja: "MDBサブメーター経由", zh: "经MDB分表" },
  "Abnormal draws": { th: "จุดใช้ไฟผิดปกติ", ja: "異常消費", zh: "异常用电" },
  "flagged today": { th: "ที่ตั้งธงวันนี้", ja: "本日検出", zh: "今日标记" },
  "Abnormal consumption · flagged by AI": { th: "การใช้ไฟผิดปกติ · AI ตั้งธงให้", ja: "異常消費 · AI検出", zh: "异常用电 · AI标记" },
  "Finding": { th: "สิ่งที่พบ", ja: "検出内容", zh: "发现" },
  "Detail": { th: "รายละเอียด", ja: "詳細", zh: "详情" },
  "Severity": { th: "ความรุนแรง", ja: "重大度", zh: "严重度" },
  "The top five machines carry most of the plant's load. Two draws are abnormal and cost money every hour: Chiller B is pulling +15% versus its own baseline (condenser fouling — also the plant's next likely failure), and the compressed-air system keeps the night base-load +20% above what an idle plant needs. Both fixes are already in the action list.": { th: "เครื่อง 5 อันดับแรกแบกโหลดส่วนใหญ่ของโรงงาน มีการใช้ไฟผิดปกติ 2 จุดที่เสียเงินทุกชั่วโมง: Chiller B กินไฟเกิน baseline ของตัวเอง +15% (คอนเดนเซอร์ตัน — และเป็นตัวเสี่ยงพังตัวถัดไปด้วย) และระบบอัดอากาศทำให้ base-load กลางคืนสูงเกินจำเป็น +20% ทั้งสองเรื่องอยู่ในรา·ารมาตรการแล้ว", ja: "上位5設備が工場負荷の大半を占有。異常消費が2件：Chiller Bは自身のベースライン比+15%（凝縮器汚れ、次の故障候補でもある）、圧縮空気系統が夜間ベース負荷を+20%押し上げ。両対策はアクションリスト登録済み。", zh: "前五台设备承担工厂大部分负荷。两处异常每小时都在耗钱：Chiller B高于自身基线+15%（冷凝器结垢，也是下一个可能故障点），空压系统使夜间基础负荷高出+20%。两项对策均已列入行动清单。" },
  "This month's bill": { th: "บิลเดือนนี้", ja: "今月の請求", zh: "本月账单" },
  "Bill MTD": { th: "บิลถึงวันนี้", ja: "今月累計請求", zh: "本月累计" },
  "days": { th: "วัน", ja: "日間", zh: "天" },
  "On-peak energy": { th: "ค่าไฟ on-peak", ja: "オンピーク電力量料金", zh: "峰时电费" },
  "of the bill": { th: "ของทั้งบิล", ja: "請求比", zh: "占账单" },
  "contract breach · Jun 24": { th: "เกินสัญญา · 24 มิ.ย.", ja: "契約超過 · 6/24", zh: "超约 · 6月24日" },
  "Six-month bill history": { th: "ประวัติบิล 6 เดือน", ja: "6ヶ月請求履歴", zh: "6个月账单历史" },
  "Month": { th: "เดือน", ja: "月", zh: "月份" },
  "Demand": { th: "ดีมานด์", ja: "デマンド", zh: "需量" },
  "Penalty": { th: "ค่าปรับ", ja: "ペナルティ", zh: "罚款" },
  "Cost recommendations": { th: "ข้อเสนอด้านค่าไฟ", ja: "コスト提言", zh: "电费建议" },
  "Shift the three recommended loads off-peak": { th: "ย้ายโหลดที่แนะนำ 3 ตัวไปช่วง off-peak", ja: "推奨3負荷をオフピークへシフト", zh: "将3项推荐负荷移至谷时" },
  "saves": { th: "ประหยัด", ja: "削減", zh: "节省" },
  "Right-size the demand contract 3,000 → 2,900 kW once the shaved peak holds — ~฿13K/month, no capex": { th: "ปรับสัญญาดีมานด์ 3,000 → 2,900 kW เมื่อพีคใหม่นิ่งแล้ว — ~฿13K/เดือน ไม่ต้องลงทุน", ja: "ピーク安定後に契約を3,000→2,900kWへ適正化 — 月約1.3万฿、投資ゼロ", zh: "峰值稳定后将合约调至2,900 kW — 每月约฿13K，零投资" },
  "The month-to-date bill stands at ฿1.27M — demand charge ฿399K (31%), one breach penalty ฿29.9K. With 62% of energy consumed on-peak (฿4.33 vs ฿2.64 off-peak), the biggest lever is shifting deferrable loads off-peak; the recommended plan is worth roughly ฿121K per month.": { th: "บิลสะสมเดือนนี้อยู่ที่ ฿1.27M — เป็นค่าดีมานด์ ฿399K (31%) และค่าปรับจากการเกินสัญญา 1 ครั้ง ฿29.9K พลังงาน 62% ถูกใช้ช่วง on-peak (฿4.33 เทียบ ฿2.64 ช่วง off-peak) คันโ·ที่ใหญ่ที่สุดคือย้ายโหลดที่เลื่อนได้ไป off-peak — แผนที่แนะนำมีมูลค่าราว ฿121K ต่อเดือน", ja: "今月累計請求は127万฿ — デマンド料金39.9万฿（31%）、超過ペナルティ2.99万฿。エネルギーの62%がオンピーク消費（4.33 vs 2.64฿/kWh）のため、最大のレバーは負荷のオフピークシフト — 推奨プランは月約12.1万฿相当。", zh: "本月累计账单฿1.27M — 需量电费฿399K（31%），一次超约罚款฿29.9K。62%能耗在峰时（฿4.33对฿2.64），最大杠杆是将可延迟负荷移至谷时 — 推荐方案每月价值约฿121K。" },
  "Savings KPIs": { th: "ตัวชี้วัดผลประหยัด", ja: "省エネKPI", zh: "节能KPI" },
  "Verified · 6 months": { th: "พิสูจน์แล้ว · 6 เดือน", ja: "検証済 · 6ヶ月", zh: "已核证 · 6个月" },
  "vs pre-AI baseline": { th: "เทียบ baseline ก่อนใช้ AI", ja: "AI導入前比", zh: "对比AI前基线" },
  "Last month": { th: "เดือนล่าสุด", ja: "先月", zh: "上月" },
  "and still climbing": { th: "และยังไต่ขึ้นต่อเนื่อง", ja: "なお上昇中", zh: "仍在增长" },
  "Active measures": { th: "มาตรการที่เดินอยู่", ja: "稼働中施策", zh: "运行中措施" },
  "per year": { th: "ต่อปี", ja: "年間", zh: "每年" },
  "Ready to approve": { th: "พร้อมอนุมัติ", ja: "承認待ち", zh: "待批准" },
  "needs": { th: "ใช้งบ", ja: "必要額", zh: "需" },
  "Measure by measure": { th: "ไล่ทีละมาตรการ", ja: "施策別内訳", zh: "逐项措施" },
  "active": { th: "เดินอยู่", ja: "稼働中", zh: "运行中" },
  "ready": { th: "พร้อมเริ่ม", ja: "準備完了", zh: "就绪" },
  "planned": { th: "อยู่ในแผน", ja: "計画中", zh: "计划中" },
  "Recommendation": { th: "ข้อเสนอแนะ", ja: "提言", zh: "建议" },
  "Approve Compressor Sequencing and Chiller Optimization — ฿1.47M/yr for ฿380K, both verified by the same meters within one month of go-live": { th: "อนุมัติ Compressor Sequencing และ Chiller Optimization — ได้ ฿1.47M/ปี ด้วยงบ ฿380K และมิเตอร์ชุดเดิมจะพิสูจน์ผลได้ภายใน 1 เดือนหลังเริ่ม", ja: "コンプレッサー順序制御とチラー最適化を承認 — 38万฿の投資で年147万฿、稼働後1ヶ月以内に同メーターで検証可能", zh: "批准空压机排序与冷机优化 — 投入฿380K获得฿1.47M/年，上线1个月内由同批电表核证" },
  "Verified savings have climbed six months straight — ฿42K to ฿128K per month, ฿538K cumulative — measured against the pre-AI baseline, not estimated. Measures already running are worth ฿1.54M a year at zero capex. The next ฿1.47M a year sits in two ready-to-approve measures needing ฿380K of capex with paybacks of five months or less.": { th: "ผลประหยัดที่พิสูจน์แล้วไต่ขึ้น 6 เดือนติด — จาก ฿42K เป็น ฿128K ต่อเดือน รวมสะสม ฿538K — วัดเทียบ baseline ก่อนใช้ AI ไม่ใช่การประมาณ มาตรการที่เดินอยู่มีมูลค่า ฿1.54M ต่อปีโดยไม่ใช้เงินลงทุน ส่วนอีก ฿1.47M ต่อปีรออยู่ในมาตรการพร้อมอนุมัติ 2 ตัว ใช้งบ ฿380K คืนทุนไม่เกิน 5 เดือน", ja: "検証済み削減額は6ヶ月連続増加 — 月4.2万→12.8万฿、累計53.8万฿（AI導入前ベースライン比、推定値ではない）。稼働中施策は投資ゼロで年154万฿相当。次の年147万฿は承認待ち2施策（投資38万฿、回収5ヶ月以内）。", zh: "核证节省连续6个月增长 — 每月฿42K至฿128K，累计฿538K — 对照AI前基线实测而非估算。运行中措施零投资年价值฿1.54M。另有两项待批措施年价值฿1.47M，需投入฿380K，回收期不超过5个月。" },
  /* ------------------------------------------------------------ Report tab */
  "Event simulation · what-if": { th: "จำลองเหตุการณ์ · what-if", ja: "イベントシミュレーション · What-if", zh: "事件模拟 · What-if" },
  "stop simulation": { th: "หยุดจำลอง", ja: "シミュレーション停止", zh: "停止模拟" },
  "demo mode — nothing is sent to the real plant": { th: "โหมดเดโม — ไม่มีคำสั่งใดถูกส่งไปโรงงานจริง", ja: "デモモード — 実工場には何も送信されません", zh: "演示模式 — 不会向真实工厂发送任何指令" },
  "simulating — watch the twin above": { th: "กำลังจำลอง — ดูผลที่ดิจิทัลทวินด้านบน", ja: "シミュレーション中 — 上のツインをご覧ください", zh: "模拟中 — 请看上方数字孪生" },
  "Peak breach": { th: "พีคเกินสัญญา", ja: "ピーク超過", zh: "峰值超约" },
  "simultaneous loads push past the 3,000 kW contract — watch AI shed it": { th: "โหลดเดินพร้อมกันจนทะลุสัญญา 3,000 kW — ดู AI กดพีคลง", ja: "同時負荷が契約3,000kWを突破 — AIの負荷制御を確認", zh: "同时负荷突破3,000 kW合约 — 看AI如何削峰" },
  "13:40 — chillers, compressors and ovens ramp at the same time": { th: "13:40 — Chiller, Compressor และเตาอบเร่งโหลดพร้อมกัน", ja: "13:40 — チラー・コンプレッサー・オーブンが同時に負荷上昇", zh: "13:40 — 冷机、空压机与烤箱同时升载" },
  "Peak climbing — 3,050 kW, closing in on the 3,000 kW contract": { th: "พีคไต่ขึ้นแตะ 3,050 kW — จ่อสัญญา 3,000 kW", ja: "ピーク上昇 — 3,050kW、契約3,000kWに接近", zh: "峰值攀升至3,050 kW — 逼近3,000 kW合约" },
  "13:42 — peak hits 3,150 kW, contract breached · penalty ฿132.93/kW is now running": { th: "13:42 — พีคแตะ 3,150 kW เกินสัญญาแล้ว · ค่าปรับ ฿132.93/kW กำลังเดิน", ja: "13:42 — ピーク3,150kWで契約超過 · ペナルティ฿132.93/kW発生中", zh: "13:42 — 峰值达3,150 kW，已超约 · 罚款฿132.93/kW计费中" },
  "AI responds: delaying Air Comp #2 and releasing pre-cooled thermal storage": { th: "AI ตอบสนอง: เลื่อนสตาร์ท Air Comp #2 และปล่อยความเย็นที่สะสมไว้ล่วงหน้า", ja: "AI対応：Air Comp #2の始動遅延と蓄冷の放出", zh: "AI响应：延迟Air Comp #2启动并释放预冷蓄能" },
  "Peak back to 2,940 kW — under contract within 3 minutes": { th: "พีคลดเหลือ 2,940 kW — กลับเข้าใต้สัญญาภายใน 3 นาที", ja: "ピークは2,940kWへ — 3分以内に契約内へ復帰", zh: "峰值回落至2,940 kW — 3分钟内回到合约以内" },
  "Scenario result: ~฿19,900 of penalty avoided · event logged to the daily report": { th: "สรุปเหตุการณ์: กันค่าปรับได้ ~฿19,900 · บันทึกลงรายงานประจำวันแล้ว", ja: "結果：約฿19,900のペナルティ回避 · 日報に記録済み", zh: "结果：避免罚款约฿19,900 · 已记入日报" },
  "Voltage sag": { th: "ไฟตก (Voltage sag)", ja: "電圧サグ", zh: "电压暂降" },
  "Chiller B starts DOL — L2 dips below the ITIC curve": { th: "Chiller B สตาร์ทแบบ DOL — เฟส L2 ตกหลุดเส้น ITIC", ja: "Chiller B直入始動 — L2がITIC曲線を下回る", zh: "Chiller B直接启动 — L2跌破ITIC曲线" },
  "Chiller B starts direct-on-line — inrush current 6× rated": { th: "Chiller B สตาร์ทมอเตอร์แบบ DOL — กระแสพุ่ง 6 เท่าของพิกัด", ja: "Chiller B直入始動 — 突入電流が定格の6倍", zh: "Chiller B直接启动 — 浪涌电流达额定6倍" },
  "L2 dips to 76% for 120 ms — outside the ITIC curve": { th: "แรงดันเฟส L2 ตกเหลือ 76% นาน 120 ms — หลุดเส้น ITIC", ja: "L2が120msの間76%へ低下 — ITIC曲線外", zh: "L2跌至76%持续120毫秒 — 超出ITIC曲线" },
  "Two production-line PLCs at reset risk — AI checking ride-through": { th: "PLC ไลน์ผลิต 2 ตัวเสี่ยงรีเซ็ต — AI กำลังเช็ค ride-through", ja: "生産ラインPLC2台にリセットリスク — AIがライドスルー確認中", zh: "两台产线PLC有复位风险 — AI正在检查穿越能力" },
  "Root cause: DOL start. AI recommends a soft-starter on Chiller B (฿85K)": { th: "ต้นเหตุ: การสตาร์ทแบบ DOL — AI แนะนำติด soft-starter ที่ Chiller B (฿85K)", ja: "根本原因：直入始動。AIはChiller Bへのソフトスターター設置を推奨（฿85K）", zh: "根因：直接启动。AI建议为Chiller B加装软启动器（฿85K）" },
  "Back to normal — a soft-starter work order is drafted in Work Orders": { th: "กลับสู่ปกติ — ร่างใบสั่งงานติด soft-starter ไว้ให้แล้วในใบสั่งงาน", ja: "正常復帰 — ソフトスターターの作業指示を起案済み", zh: "恢复正常 — 软启动器工单已在工单中起草" },
  "Chiller B trip": { th: "Chiller B หยุดฉุกเฉิน", ja: "Chiller Bトリップ", zh: "Chiller B跳机" },
  "emergency stop on the sick chiller — watch the standby take over": { th: "เครื่องที่ป่วยหยุดฉุกเฉิน — ดูตัวสำรองรับช่วงต่อ", ja: "不調チラーの緊急停止 — 予備機の引継ぎを確認", zh: "病态冷机急停 — 看备用机接管" },
  "Chiller B trips — condenser over-temperature, emergency stop": { th: "Chiller B หยุดฉุกเฉิน — คอนเดนเซอร์ร้อนเกิน", ja: "Chiller Bトリップ — 凝縮器過熱で緊急停止", zh: "Chiller B跳机 — 冷凝器过热，紧急停机" },
  "Chilled-water temperature creeping +0.8°C — production lines at risk in ~20 min": { th: "อุณหภูมิน้ำเย็นไต่ขึ้น +0.8°C — ไลน์ผลิตจะเริ่มเสี่ยงในอีก ~20 นาที", ja: "冷水温度が+0.8°C上昇中 — 約20分で生産ラインに影響", zh: "冷冻水温上升+0.8°C — 约20分钟后产线受威胁" },
  "AI starts the standby chiller and relaxes setpoints temporarily": { th: "AI สั่งสตาร์ท Chiller สำรอง และผ่อน setpoint ชั่วคราว", ja: "AIが予備チラーを起動し設定値を一時緩和", zh: "AI启动备用冷机并临时放宽设定值" },
  "Standby chiller carrying full load — temperature stable, production untouched": { th: "Chiller สำรองรับโหลดเต็มแล้ว — อุณหภูมิคงที่ ไลน์ผลิตไม่สะดุด", ja: "予備チラーが全負荷を担当 — 温度安定、生産影響なし", zh: "备用冷机满载运行 — 温度稳定，生产未受影响" },
  "Scenario result: 0 minutes of downtime · a P1 repair work order was raised automatically": { th: "สรุปเหตุการณ์: ดาวน์ไทม์ 0 นาที · ออกใบสั่งงานซ่อมระดับ P1 อัตโนมัติแล้ว", ja: "結果：ダウンタイム0分 · P1修理指示を自動発行", zh: "结果：停机0分钟 · 已自动下达P1维修工单" },
  /* ------------------------------------------------------------ Report tab */
  "Meters only": { th: "มิเตอร์อย่างเดียว", ja: "メーターのみ", zh: "仅电表" },
  "AI on": { th: "เปิด AI", ja: "AI オン", zh: "开启AI" },
  "AI adds:": { th: "AI เพิ่มให้:", ja: "AIが追加:", zh: "AI增加：" },
  "Unlock with AI": { th: "ปลดล็อกด้วย AI", ja: "AIでロック解除", zh: "用AI解锁" },
  "scripted what-if scenarios — AI plays out a peak breach, a voltage sag or a chiller trip and shows how it would respond.": { th: "จำลองเหตุการณ์ what-if — AI เดินเรื่องพีคเกินสัญญา ไฟตก หรือ Chiller หยุด แล้วโชว์ว่าจะตอบสนองยังไง", ja: "What-ifシナリオ — AIがピーク超過・電圧サグ・チラー停止を再現し、対応方法を提示", zh: "What-if情景模拟 — AI演绎峰值超约、电压暂降或冷机跳机，并展示如何响应" },
  "the meter logs the sag — AI names the likely cause (e.g. a DOL motor start) and the exact fix for each event.": { th: "มิเตอร์บันทึกว่าไฟตก — AI บอกสาเหตุที่น่าจะเป็น (เช่น สตาร์ทมอเตอร์แบบ DOL) และวิธีแก้ที่ตรงจุดของแต่ละเหตุการณ์", ja: "メーターはサグを記録 — AIは推定原因（例：DOL始動）と各イベントの具体的な対策を提示", zh: "电表记录暂降 — AI指出可能原因（如DOL直启）并给出每次事件的具体对策" },
  "AI reads 12 months of billed peaks and recommends right-sizing the demand contract — a no-capex saving the meter can't spot on its own.": { th: "AI อ่านพีคที่ถูกคิดเงิน 12 เดือน แล้วแนะนำปรับขนาดสัญญาดีมานด์ — ประหยัดโดยไม่ต้องลงทุน ซึ่งมิเตอร์เฉยๆ มองไม่เห็น", ja: "AIが12ヶ月の課金ピークを分析し契約デマンドの適正化を提案 — メーター単体では見えない投資ゼロの削減", zh: "AI分析12个月计费峰值并建议优化需量合约 — 电表本身发现不了的零投资节省" },
  "Savings portfolio & abatement analysis": { th: "พอร์ตผลประหยัด & วิเคราะห์ต้นทุนลด", ja: "省エネポートフォリオ・削減分析", zh: "节能组合与减排分析" },
  "AI turns metered waste into a ranked list of savings measures — each with ฿/yr, capex and payback — and plots the cheapest-first curve. Meters show spend; this shows what to do about it.": { th: "AI แปลงการสูญเสี·ี่มิเตอร์จับได้ เป็นรา·ารมาตรการประหยัดที่จัดลำดับให้ — พร้อม ฿/ปี เงินลงทุน และจุดคืนทุน และวาดกราฟถูกสุดก่อน มิเตอร์บอกแค่ว่าจ่ายไปเท่าไหร่ ส่วนนี้บอกว่าควรทำอะไร", ja: "AIはメーターが捉えた無駄を、省エネ施策の優先リスト（฿/年・投資・回収付き）に変換し、安価順の曲線を描画。メーターは支出を示すが、これは対策を示す", zh: "AI将电表捕捉的浪费转化为排序的节能措施清单 — 含฿/年、投资与回收期 — 并绘制最省优先曲线。电表显示花了多少，这里显示该怎么办" },
  "AI Optimization is the AI layer": { th: "AI Optimization คือชั้น AI", ja: "AI最適化はAIレイヤー", zh: "AI优化即AI层" },
  "Meters show you the load. This is where AI acts on it — forecasting peaks, standing down idle machines and shifting load automatically to cut the bill without anyone watching.": { th: "มิเตอร์บอกแค่โหลด — ตรงนี้คือที่ AI ลงมือจริง: พยากรณ์พีค สั่งพักเครื่องที่เดินเปล่า และย้ายโหลดอัตโนมัติเพื่อลดค่าไฟ โดยไม่ต้องมีคนคอยเฝ้า", ja: "メーターは負荷を示すだけ。ここはAIが実際に動く場所 — ピーク予測、アイドル設備の待機、負荷の自動シフトで、誰も見ていなくても電気代を削減", zh: "电表只显示负荷。这里是AI真正行动之处 — 预测峰值、让空转设备待机、自动转移负荷，无人值守也能降低电费" },
  "Peak Demand Autopilot — sheds load before a contract breach": { th: "Peak Demand Autopilot — ลดโหลดก่อนจะเกินสัญญา", ja: "ピークデマンド自動制御 — 契約超過前に負荷を抑制", zh: "峰值需量自动驾驶 — 超约前削减负荷" },
  "Idle Machine Optimizer — auto-standby for machines idling too long": { th: "Idle Machine Optimizer — สั่งพักเครื่องที่เดินเปล่านานเกินไปอัตโนมัติ", ja: "アイドル設備最適化 — 長時間空転の設備を自動待機", zh: "空转设备优化 — 空转过久的设备自动待机" },
  "Off-Peak Load Shifter — moves deferrable loads to the cheap window": { th: "Off-Peak Load Shifter — ย้ายโหลดที่เลื่อนได้ไปช่วงค่าไฟถูก", ja: "オフピーク負荷シフト — 遅延可能な負荷を安価な時間帯へ", zh: "谷时负荷转移 — 将可延迟负荷移至低价时段" },
  "Sequential Start Scheduler — staggers startup to avoid a demand spike": { th: "Sequential Start Scheduler — ทยอยสตาร์ทเครื่องเพื่อเลี่ยงพีคพุ่ง", ja: "順次起動スケジューラ — 起動をずらしデマンド急増を回避", zh: "顺序启动调度 — 错峰启动以避免需量突增" },
  "AI-detected issues, ranked by baht impact": { th: "ปัญหาที่ AI ตรวจพบ จัดลำดับตามผลกระทบเป็นเงิน", ja: "AIが検出した問題を金額インパクト順に整理", zh: "AI检测的问题，按金额影响排序" },
  "One-click work orders from every recommendation": { th: "ออกใบสั่งงานจากทุกข้อเสนอได้ในคลิกเดียว", ja: "各提案からワンクリックで作業指示", zh: "每条建议一键生成工单" },
  /* ------------------------------------------------------------ Report tab */
  "Live signal & harmonics": { th: "สัญญาณสด & ฮาร์มอนิก", ja: "ライブ信号・高調波", zh: "实时信号与谐波" },
  "Power factor & standards": { th: "PF & มาต°าน", ja: "力率・規格", zh: "功率因数与标准" },
  "Disturbance events": { th: "เหตุการณ์รบกวน", ja: "外乱イベント", zh: "扰动事件" },
  /* ------------------------------------------------------------ Report tab */
  "Disturbances today": { th: "เหตุการณ์รบกวนวันนี้", ja: "本日の外乱", zh: "今日扰动" },
  "total": { th: "รวม", ja: "合計", zh: "合计" },
  "times today": { th: "ครั้งวันนี้", ja: "回 · 本日", zh: "次 · 今日" },
  "filtering ↓": { th: "กำลังกรอง ↓", ja: "フィルタ中 ↓", zh: "筛选中 ↓" },
  "shown": { th: "แสดง", ja: "件表示", zh: "已显示" },
  "clear filter": { th: "ล้างตัวกรอง", ja: "フィルタ解除", zh: "清除筛选" },
  "click a card to filter · click row to replay": { th: "คลิกการ์ดเพื่อกรอง · คลิกแถวเพื่อรีเพลย์", ja: "カードで絞込 · 行で再生", zh: "点卡片筛选 · 点行回放" },
  "No events of this type today.": { th: "วันนี้ไม่มีเหตุการณ์ประเภทนี้", ja: "本日この種のイベントなし", zh: "今日无此类事件" },
  "Report range": { th: "ช่วงรายงาน", ja: "レポート期間", zh: "报告范围" },
  "custom": { th: "กำหนดเอง", ja: "カスタム", zh: "自定义" },
  "events in range": { th: "เหตุการณ์ในช่วงนี้", ja: "件（期間内）", zh: "起（范围内）" },
  "Power quality events": { th: "เหตุการณ์คุณภาพไฟฟ้า", ja: "電力品質イベント", zh: "电能质量事件" },
  "Count": { th: "จำนวน", ja: "件数", zh: "次数" },
  "Worst": { th: "หนักสุด", ja: "最悪", zh: "最严重" },
  "Typical source": { th: "แหล่งที่พบบ่อย", ja: "主な原因", zh: "常见来源" },
  "Notable events": { th: "เหตุการณ์สำคัญ", ja: "主なイベント", zh: "重点事件" },
  "Power quality event report": { th: "รายงานเหตุการณ์คุณภาพไฟฟ้า", ja: "電力品質イベントレポート", zh: "电能质量事件报告" },
  "events": { th: "เหตุการณ์", ja: "件", zh: "起" },
  "Incomer PQ meter": { th: "มิเตอร์คุณภาพไฟฟ้าจุดรับไฟ", ja: "引込PQメーター", zh: "进线电能质量表" },
  "Summary · by disturbance type": { th: "สรุป · แ·ตามชนิดเหตุการณ์", ja: "サマリー · 外乱種別", zh: "汇总 · 按扰动类型" },
  "By type · worst case & source": { th: "แ·ตามชนิด · หนักสุด & แหล่งที่มา", ja: "種別 · 最悪ケースと原因", zh: "按类型 · 最严重与来源" },
  "ITIC violations": { th: "หลุดเกณฑ์ ITIC", ja: "ITIC違反", zh: "ITIC越限" },
  "Generated by SpareX FactoryOS™ · EnergyAI — captured by the incomer power-quality meter": { th: "สร้างโดย SpareX FactoryOS™ · EnergyAI — บันทึกจากมิเตอร์คุณภาพไฟฟ้าที่จุดรับไฟ", ja: "SpareX FactoryOS™ · EnergyAI作成 — 引込電力品質メーターで記録", zh: "由SpareX FactoryOS™ · EnergyAI生成 — 由进线电能质量表采集" },
  /* ------------------------------------------------------------ Report tab */
  "Pull event report": { th: "ดึงรายงานเหตุการณ์", ja: "イベントレポート出力", zh: "导出事件报告" },
  /* ------------------------------------------------------------ Report tab */
  "+ more events — see the full history in the PDF / Excel above": { th: "+ มีเหตุการณ์เพิ่ม — ดูครบในไฟล์ PDF / Excel ด้านบน", ja: "+ 他にもイベントあり — 上の PDF / Excel で全件確認", zh: "+ 还有更多事件 — 在上方 PDF / Excel 查看完整记录" },
  /* ------------------------------------------------------------ Report tab */
  "Measured value": { th: "ค่าที่วัดได้", ja: "測定値", zh: "测量值" },
  "Over standard": { th: "เกินมาต°าน", ja: "基準超過", zh: "超标" },
  "Location": { th: "จุดที่เจอ", ja: "検出箇所", zh: "发现位置" },
  "Over limit": { th: "เกิน", ja: "超過", zh: "超限" },
  "Watch": { th: "เฝ้าระวัง", ja: "要注視", zh: "关注" },
  /* ------------------------------------------------------------ Report tab */
  "AI Analysis": { th: "วิเคราะห์ด้วย AI", ja: "AI分析", zh: "AI分析" },
  "confidence": { th: "มั่นใจ", ja: "信頼度", zh: "置信度" },
  "How AI knows": { th: "AI รู้ได้ยังไง", ja: "AIが判断した根拠", zh: "AI如何得知" },
  "evidence": { th: "หลักฐาน", ja: "根拠", zh: "证据" },
  "No-cost fix": { th: "แก้แบบไม่ต้องลงทุน", ja: "無投資の対策", zh: "零成本方案" },
  "do it now": { th: "ทำได้เลย", ja: "今すぐ実施", zh: "立即可做" },
  "Investment fix": { th: "แก้แบบต้องลงทุน", ja: "投資が必要な対策", zh: "需投资方案" },
  "Result if fixed": { th: "ผลลัพธ์ถ้าแก้", ja: "対策後の効果", zh: "改善后效果" },
  /* harmonic diagnostic flow: found → where → cause → fix */
  "Found": { th: "เจออะไร", ja: "検出内容", zh: "发现" },
  "Where from": { th: "จากที่ไหน", ja: "発生源", zh: "来源" },
  "Fix": { th: "แก้ยังไง", ja: "対策", zh: "如何解决" },
  "meter": { th: "จากมิเตอร์", ja: "メーター", zh: "来自电表" },
  "Harmonics": { th: "ฮาร์มอนิก", ja: "高調波", zh: "谐波" },
  "exceed the individual limit": { th: "เกินลิมิตรายตัว", ja: "個別上限を超過", zh: "超过单项限值" },
  "all harmonic orders within limits": { th: "ทุกอันดับฮาร์มอนิกอยู่ในลิมิต", ja: "全次数が上限内", zh: "各次谐波均在限值内" },
  "6-pulse VFD drives — variable-speed motors (fans / pumps / compressors)": { th: "ไดรฟ์ VFD แบบ 6 พัลส์ — มอเตอร์ปรับรอบ (พัดลม / ปั๊ม / คอมเพรสเซอร์)", ja: "6パルスVFD — 可変速モーター（ファン/ポンプ/コンプレッサー）", zh: "6脉冲变频器 — 变速电机（风机/水泵/压缩机）" },
  "single-phase electronics (power supplies / LED lighting) on the neutral": { th: "อุปกรณ์อิเล็กทรอนิกส์เฟสเดียว (พาวเวอร์ซัพพลาย / ไฟ LED) บนสายนิวทรัล", ja: "中性線上の単相電子機器（電源/LED照明）", zh: "中性线上的单相电子设备（电源/LED照明）" },
  "no dominant harmonic source": { th: "ไม่พบแหล่งฮาร์มอนิกเด่นชัด", ja: "支配的な高調波源なし", zh: "无显著谐波源" },
  "a VFD input rectifier draws current in sharp pulses, which naturally creates the 5th & 7th harmonics": { th: "หน้าอินพุตของ VFD เป็นวงจรเรียงกระแส ดึงกระแสเป็นจังหวะแหลม จึงเกิดฮาร์มอนิกที่ 5 และ 7 เป็นธรรมชาติ", ja: "VFDの入力整流器がパルス状に電流を引き、5次・7次高調波が発生", zh: "变频器输入整流器以尖峰脉冲取电，自然产生5次和7次谐波" },
  "single-phase loads create 3rd harmonics that add up on the neutral instead of cancelling": { th: "โหลดเฟสเดียวสร้างฮาร์มอนิกที่ 3 ที่มาบวกกันบนสายนิวทรัลแทนที่จะหักล้างกัน", ja: "単相負荷が3次高調波を生み、中性線で相殺されず加算される", zh: "单相负荷产生3次谐波，在中性线上叠加而非抵消" },
  "distortion is low — no clear source": { th: "ความเพี้ยนต่ำ — ยังไม่พบแหล่งชัดเจน", ja: "歪みは小さい — 明確な源なし", zh: "畸变较低 — 无明确来源" },
  "the PF-correction bank sits near the 5th-harmonic frequency, a resonance risk that can make the capacitors fail.": { th: "คาปาซิเตอร์แก้ PF อยู่ใกล้ความถี่ฮาร์มอนิกที่ 5 เสี่ยงเรโซแนนซ์จนคาปาซิเตอร์เสียหาย", ja: "力率改善バンクが5次高調波周波数付近にあり、共振でコンデンサが故障する恐れ", zh: "功率因数补偿组接近5次谐波频率，存在谐振导致电容损坏的风险" },
  "a 7% detuned reactor (~3.8th) so the PF bank can't resonate": { th: "detuned reactor 7% (~3.8) กันไม่ให้คาปาซิเตอร์เรโซแนนซ์", ja: "7%デチューンドリアクトル（~3.8次）で共振を防止", zh: "加装7%失谐电抗器（~3.8次）防止电容谐振" },
  "AI harmonic findings": { th: "ผลวิเคราะห์ฮาร์มอนิกโดย AI", ja: "AI高調波分析結果", zh: "AI谐波分析结果" },
  "AI balance findings": { th: "ผลวิเคราะห์สมดุล 3 เฟสโดย AI", ja: "AI三相バランス分析結果", zh: "AI三相平衡分析结果" },
  "Phases are balanced — within NEMA, no motor derating needed.": { th: "สามเฟสสมดุลดี — อยู่ในเกณฑ์ NEMA ไม่ต้องลดพิกัดมอเตอร์", ja: "三相はバランス良好 — NEMA基準内、モーターのディレーティング不要", zh: "三相平衡良好 — 在NEMA范围内，无需降额" },
  "ranked by severity": { th: "เรียงตามความรุนแรง", ja: "深刻度順", zh: "按严重程度排序" },
  "prevents capacitor failure & downtime": { th: "ป้องกันคาปาซิเตอร์เสียหายและดาวน์ไทม์", ja: "コンデンサ故障とダウンタイムを防止", zh: "防止电容损坏与停机" },
  "prevents unplanned downtime": { th: "ป้องกันดาวน์ไทม์ที่ไม่ได้วางแผน", ja: "予期せぬダウンタイムを防止", zh: "防止意外停机" },
  "No harmonic issues — every order is within its individual limit.": { th: "ไม่พบปัญหาฮาร์มอนิก — ทุกอันดับอยู่ในลิมิตรายตัว", ja: "高調波問題なし — 全次数が個別上限内", zh: "无谐波问题 — 各次均在单项限值内" },
  "Locate in Digital Twin": { th: "หาตำแหน่งในดิจิทัลทวิน", ja: "デジタルツインで位置特定", zh: "在数字孪生中定位" },
  "AI power-quality analysis": { th: "วิเคราะห์คุณภาพไฟฟ้าด้วย AI", ja: "AI電力品質分析", zh: "AI电能质量分析" },
  "Meters show the disturbance. This is where AI names the exact source, ranks the fix by baht saved, and points you at the machine to inspect.": { th: "มิเตอร์บอกแค่ว่ามีการรบกวน — ตรงนี้คือที่ AI ระบุต้นตอที่แท้จริง จัดลำดับการแก้ตามเงินที่ประหยัดได้ และชี้เครื่องที่ต้องไปตรวจ", ja: "メーターは外乱を示すだけ。ここはAIが真の原因を特定し、削減額で対策を優先順位付けし、点検すべき設備を示す場所", zh: "电表只显示有扰动。这里是AI指出真正来源、按节省金额排序对策并指明待检设备之处" },
  "Root cause per disturbance (sag, swell, flicker, transient)": { th: "รากสาเหตุของแต่ละการรบกวน (ไฟตก/เกิน/กระพริบ/กระชาก)", ja: "外乱ごとの根本原因（サグ/スウェル/フリッカ/過渡）", zh: "每种扰动的根因（暂降/暂升/闪变/瞬变）" },
  "Evidence traced from the waveform + time-stamps": { th: "หลักฐานจากรูปคลื่น + เวลาที่บันทึก", ja: "波形とタイムスタンプからの証拠", zh: "来自波形与时间戳的证据" },
  "Recommended fix with ฿/yr impact": { th: "วิธีแก้ที่แนะนำพร้อมผลเป็น ฿/ปี", ja: "推奨対策と฿/年の効果", zh: "建议对策及฿/年影响" },
  "One-click locate the source in the Digital Twin": { th: "กดครั้งเดียวหาต้นตอในดิจิทัลทวิน", ja: "ワンクリックでデジタルツインの原因位置へ", zh: "一键在数字孪生中定位来源" },
  "Analysis indicates the disturbances trace to three sources": { th: "การวิเคราะห์ชี้ว่าการรบกวนมาจาก 3 ต้นตอ", ja: "分析によると外乱は3つの原因に起因", zh: "分析显示扰动源于三个来源" },
  "— Chiller B (sags), the MDB capacitor bank (transients & overvoltage) and the welding bay (flicker). Clearing all of them removes ~85% of events and avoids": { th: "— Chiller B (ไฟตก), คาปาซิเตอร์แบงก์ที่ MDB (ไฟกระชาก & แรงดันเกิน) และโซนงานเชื่อม (ไฟกระพริบ) แก้ครบทั้งสามลดเหตุการณ์ได้ ~85% และเลี่ยงได้", ja: "— Chiller B（サグ）、MDBコンデンサバンク（過渡・過電圧）、溶接エリア（フリッカ）。全て解消で事象を約85%削減し回避", zh: "— Chiller B（暂降）、MDB电容器组（瞬变与过压）和焊接区（闪变）。全部解决可减少约85%事件并避免" },
  "in equipment damage and downtime.": { th: "ความเสียหายของอุปกรณ์และดาวน์ไทม์", ja: "設備損傷とダウンタイムを", zh: "设备损坏与停机损失" },
  "Power quality summary & compliance": { th: "สรุปคุณภาพไฟฟ้า & การปฏิบัติตามมาต°าน", ja: "電力品質サマリー・規格適合", zh: "电能质量汇总与合规" },
  "PQ score · THD · power factor · IEEE-519 / EN 50160 compliance": { th: "คะแนน PQ · THD · เพาเวอร์แฟกเตอร์ · การปฏิบัติตาม IEEE-519 / EN 50160", ja: "PQスコア · THD · 力率 · IEEE-519 / EN 50160適合", zh: "PQ评分 · THD · 功率因数 · IEEE-519 / EN 50160合规" },
  "Power quality summary & compliance report": { th: "รายงานสรุปคุณภาพไฟฟ้า & การปฏิบัติตามมาต°าน", ja: "電力品質サマリー・規格適合レポート", zh: "电能质量汇总与合规报告" },
  "PQ score, THD, power factor, IEEE-519 / EN 50160 compliance and the AI root-cause table — one page, ready to send.": { th: "คะแนน PQ, THD, เพาเวอร์แฟกเตอร์, การปฏิบัติตาม IEEE-519 / EN 50160 และตารางรากสาเหตุจาก AI — หน้าเดียว พร้อมส่ง", ja: "PQスコア・THD・力率・IEEE-519/EN 50160適合とAI根本原因表 — 1ページ、送信準備完了", zh: "PQ评分、THD、功率因数、IEEE-519/EN 50160合规及AI根因表 — 一页，可直接发送" },
  "Root causes & fixes · by AI": { th: "รากสาเหตุ & วิธีแก้ · โดย AI", ja: "根本原因と対策 · AI", zh: "根因与对策 · AI" },
  "Root cause": { th: "รากสาเหตุ", ja: "根本原因", zh: "根因" },
};
