import type { TrDict } from "./types";

/** Operations / Production Intelligence module views. */
export const operationsDict: TrDict = {
  // —— sub-nav tab labels ——
  "Live Production": { th: "การผลิตเรียลไทม์", ja: "ライブ生産", zh: "实时生产" },
  "OEE & Downtime": { th: "OEE และดาวน์ไทม์", ja: "OEEとダウンタイム", zh: "OEE与停机" },
  "Production Cost": { th: "ต้นทุนการผลิต", ja: "生産原価", zh: "生产成本" },
  "Bottlenecks": { th: "คอขวด", ja: "ボトルネック", zh: "瓶颈" },
  "AI Optimization": { th: "การปรับให้เหมาะสมด้วย AI", ja: "AI最適化", zh: "AI优化" },

  // —— GenericView placeholder ——
  "runs on the live production model — combining OEE, downtime, cost and profit signals. Ask the Production Copilot to generate this analysis or take action.": { th: "ทำงานบนโมเดลการผลิตเรียลไทม์ — รวมสัญญาณ OEE ดาวน์ไทม์ ต้นทุน และกำไร ขอให้ Production Copilot สร้างการวิเคราะห์นี้หรือดำเนินการ", ja: "ライブ生産モデル上で動作 — OEE、ダウンタイム、原価、利益のシグナルを統合。Production Copilotに分析生成や対応を依頼してください。", zh: "运行于实时生产模型 — 综合OEE、停机、成本与利润信号。可请Production Copilot生成此分析或采取行动。" },
  "Ask AI about": { th: "ถาม AI เกี่ยวกับ", ja: "AIに質問:", zh: "向AI询问" },

  // —— GenericView leaf labels (reachable via wired tabs) ——
  "Cost per Unit": { th: "ต้นทุนต่อหน่วย", ja: "単位当たり原価", zh: "单位成本" },
  "Bottleneck": { th: "คอขวด", ja: "ボトルネック", zh: "瓶颈" },
  "Production by Line": { th: "การผลิตแยกตามไลน์", ja: "ライン別生産", zh: "按产线生产" },
  "Production by Machine": { th: "การผลิตแยกตามเครื่องจักร", ja: "設備別生産", zh: "按设备生产" },
  "Shift Performance": { th: "ประสิทธิภาพตามกะ", ja: "シフト実績", zh: "班次绩效" },
  "Downtime Analysis": { th: "การวิเคราะห์ดาวน์ไทม์", ja: "ダウンタイム分析", zh: "停机分析" },
  "Root Cause": { th: "สาเหตุที่แท้จริง", ja: "根本原因", zh: "根本原因" },
  "Profit per Product": { th: "กำไรต่อผลิตภัณฑ์", ja: "製品別利益", zh: "各产品利润" },
  "Executive Summary": { th: "สรุปสำหรับผู้บริหาร", ja: "エグゼクティブサマリー", zh: "高管摘要" },
  "Daily AI Summary": { th: "สรุปประจำวันด้วย AI", ja: "AI日次サマリー", zh: "AI每日摘要" },
  "Opportunity Detection": { th: "การตรวจจับโอกาส", ja: "機会検出", zh: "机会识别" },
  "Recommended Actions": { th: "การดำเนินการที่แนะนำ", ja: "推奨アクション", zh: "建议措施" },
  "What-if Analysis": { th: "การวิเคราะห์ What-if", ja: "What-if分析", zh: "假设分析" },
  "Capacity Simulation": { th: "การจำลองกำลังการผลิต", ja: "能力シミュレーション", zh: "产能仿真" },
  "ROI Simulation": { th: "การจำลอง ROI", ja: "ROIシミュレーション", zh: "ROI仿真" },
  "AI Chat": { th: "แชท AI", ja: "AIチャット", zh: "AI对话" },
  "Ask Production AI": { th: "ถาม AI การผลิต", ja: "生産AIに質問", zh: "询问生产AI" },

  // —— KPI labels ——
  "Plant OEE": { th: "OEE ของโรงงาน", ja: "工場OEE", zh: "工厂OEE" },
  "Output · Today": { th: "ผลผลิต · วันนี้", ja: "産出 · 本日", zh: "产出 · 今日" },
  "Cost / Unit": { th: "ต้นทุน / หน่วย", ja: "原価 / 単位", zh: "成本 / 单位" },
  "Profit · Today": { th: "กำไร · วันนี้", ja: "利益 · 本日", zh: "利润 · 今日" },
  "Throughput": { th: "อัตราการผลิต", ja: "スループット", zh: "产能吞吐" },
  "Target Attainment": { th: "การบรรลุเป้าหมาย", ja: "目標達成率", zh: "目标达成" },
  "Availability": { th: "ความพร้อมใช้งาน", ja: "稼働率", zh: "可用率" },
  "Performance": { th: "สมรรถนะ", ja: "性能", zh: "性能" },
  "Quality": { th: "คุณภาพ", ja: "品質", zh: "质量" },
  "Total Downtime": { th: "ดาวน์ไทม์รวม", ja: "総ダウンタイム", zh: "总停机" },
  "Events": { th: "เหตุการณ์", ja: "イベント", zh: "事件" },
  "Gross Margin": { th: "อัตรากำไรขั้นต้น", ja: "粗利率", zh: "毛利率" },
  "Production Health": { th: "สุขภาพการผลิต", ja: "生産ヘルス", zh: "生产健康度" },
  "Hidden Loss": { th: "การสูญเสียแฝง", ja: "隠れ損失", zh: "隐性损失" },
  "Opportunities": { th: "โอกาส", ja: "機会", zh: "机会" },
  "Baseline OEE": { th: "OEE พื้นฐาน", ja: "ベースラインOEE", zh: "基线OEE" },
  "Projected Gain": { th: "ผลตอบแทนที่คาดการณ์", ja: "予測改善", zh: "预计增益" },
  "Payback": { th: "ระยะคืนทุน", ja: "回収期間", zh: "回收期" },
  "Top Machine": { th: "เครื่องจักรอันดับหนึ่ง", ja: "トップ設備", zh: "最佳设备" },
  "Slowest": { th: "ช้าที่สุด", ja: "最遅", zh: "最慢" },
  "Best Shift": { th: "กะที่ดีที่สุด", ja: "最良シフト", zh: "最佳班次" },
  "Productivity": { th: "ผลิตภาพ", ja: "生産性", zh: "生产率" },
  "Efficiency": { th: "ประสิทธิภาพ", ja: "効率", zh: "效率" },
  "Planned Stops": { th: "การหยุดตามแผน", ja: "計画停止", zh: "计划停机" },
  "Unplanned Stops": { th: "การหยุดนอกแผน", ja: "計画外停止", zh: "非计划停机" },
  "Ideal Cycle": { th: "รอบเวลาในอุดมคติ", ja: "理想サイクル", zh: "理想节拍" },
  "Speed Loss": { th: "การสูญเสียความเร็ว", ja: "速度ロス", zh: "速度损失" },
  "Defects": { th: "ของเสีย", ja: "不良", zh: "缺陷" },
  "Scrap": { th: "เศษเสีย", ja: "スクラップ", zh: "废品" },
  "Top Cause": { th: "สาเหตุหลัก", ja: "主要原因", zh: "主要原因" },
  "Share": { th: "สัดส่วน", ja: "割合", zh: "占比" },
  "Avoidable": { th: "หลีกเลี่ยงได้", ja: "回避可能", zh: "可避免" },
  "Utilization": { th: "อัตราการใช้งาน", ja: "稼働率", zh: "利用率" },
  "Best Line": { th: "ไลน์ที่ดีที่สุด", ja: "最良ライン", zh: "最佳产线" },
  "Worst Line": { th: "ไลน์ที่แย่ที่สุด", ja: "最劣ライン", zh: "最差产线" },
  "Top Product": { th: "ผลิตภัณฑ์อันดับหนึ่ง", ja: "トップ製品", zh: "最佳产品" },
  "Best Margin": { th: "อัตรากำไรที่ดีที่สุด", ja: "最良利益率", zh: "最佳利润率" },
  "Cost · MTD": { th: "ต้นทุน · สะสมเดือนนี้", ja: "原価 · 月初来", zh: "成本 · 本月至今" },
  "vs Budget": { th: "เทียบงบประมาณ", ja: "予算比", zh: "对比预算" },
  "Total Upside": { th: "ศักยภาพรวม", ja: "総アップサイド", zh: "总潜在收益" },
  "Quick Wins": { th: "ผลลัพธ์ที่ได้เร็ว", ja: "クイックウィン", zh: "速赢项" },
  "Actions": { th: "การดำเนินการ", ja: "アクション", zh: "措施" },
  "Est. Benefit": { th: "ผลประโยชน์โดยประมาณ", ja: "推定効果", zh: "预计收益" },
  "Auto-applicable": { th: "ปรับใช้อัตโนมัติได้", ja: "自動適用可", zh: "可自动应用" },

  // —— Executive Overview ——
  "AI Production Summary": { th: "สรุปการผลิตด้วย AI", ja: "AI生産サマリー", zh: "AI生产摘要" },
  "Output is": { th: "ผลผลิตอยู่ที่", ja: "産出は", zh: "产出为" },
  "vs. plan. Line C is exceeding target;": { th: "เทียบกับแผน · Line C เกินเป้าหมาย;", ja: "計画比。Line Cは目標超過;", zh: "对比计划。Line C超出目标;" },
  "is dragging plant OEE on changeover losses (~฿15k/day). Cutting Line B changeover recovers ~4 OEE points.": { th: "กำลังฉุด OEE ของโรงงานจากการสูญเสียช่วงเปลี่ยนรุ่น (~฿15k/วัน) การลดเวลาเปลี่ยนรุ่น Line B กู้คืน OEE ได้ ~4 จุด", ja: "段取り替え損失で工場OEEを押し下げています (~฿15k/日)。Line Bの段取り替え短縮でOEE約4ポイント回復。", zh: "因换型损失拖累工厂OEE (~฿15k/天)。缩短Line B换型可回收约4个OEE点。" },
  "OEE · 30-day trend": { th: "OEE · แนวโน้ม 30 วัน", ja: "OEE · 30日トレンド", zh: "OEE · 30天趋势" },
  "Output by line · today": { th: "ผลผลิตแยกตามไลน์ · วันนี้", ja: "ライン別産出 · 本日", zh: "按产线产出 · 今日" },

  // —— OEE Dashboard ——
  "OEE composition · 30-day": { th: "องค์ประกอบ OEE · 30 วัน", ja: "OEE構成 · 30日", zh: "OEE构成 · 30天" },

  // —— Health Score ——
  "Production Health Score": { th: "คะแนนสุขภาพการผลิต", ja: "生産ヘルススコア", zh: "生产健康评分" },
  "Healthy": { th: "แข็งแรงดี", ja: "良好", zh: "健康" },
  "Schedule Adherence": { th: "การทำตามกำหนดการ", ja: "スケジュール遵守", zh: "排程达成" },
  "Uptime": { th: "เวลาทำงาน", ja: "稼働時間", zh: "运行时间" },
  "Cost Control": { th: "การควบคุมต้นทุน", ja: "原価管理", zh: "成本控制" },

  // —— What-if Simulation ——
  "What-if scenario": { th: "สถานการณ์จำลอง What-if", ja: "What-ifシナリオ", zh: "假设情景" },
  "Cut Line B changeover": { th: "ลดเวลาเปลี่ยนรุ่น Line B", ja: "Line Bの段取り替え短縮", zh: "缩短Line B换型" },
  "Reduce scrap": { th: "ลดเศษเสีย", ja: "スクラップ削減", zh: "减少废品" },
  "Add overtime shift": { th: "เพิ่มกะโอที", ja: "残業シフト追加", zh: "增加加班班次" },
  "The simulator replays today's production model through your scenario.": { th: "เครื่องจำลองจะเล่นโมเดลการผลิตของวันนี้ผ่านสถานการณ์ของคุณ", ja: "シミュレーターは本日の生産モデルをあなたのシナリオで再現します。", zh: "模拟器将按你的情景重放今日的生产模型。" },
  "Projected impact": { th: "ผลกระทบที่คาดการณ์", ja: "予測インパクト", zh: "预计影响" },
  "Profit gain · monthly": { th: "กำไรที่เพิ่มขึ้น · รายเดือน", ja: "利益増加 · 月次", zh: "利润增益 · 每月" },
  "OEE gain": { th: "OEE ที่เพิ่มขึ้น", ja: "OEE改善", zh: "OEE增益" },
  "Extra output": { th: "ผลผลิตส่วนเพิ่ม", ja: "追加産出", zh: "额外产出" },
  "Ask AI to plan the rollout": { th: "ให้ AI วางแผนการติดตั้งใช้งาน", ja: "AIに展開計画を依頼", zh: "让AI规划推行方案" },

  // —— Production Copilot ——
  "Production Copilot": { th: "Production Copilot", ja: "Production Copilot", zh: "Production Copilot" },
  "Ask anything about production — grounded in live data": { th: "ถามอะไรก็ได้เกี่ยวกับการผลิต — อ้างอิงจากข้อมูลปัจจุบัน", ja: "生産について何でも質問 — ライブデータに基づく", zh: "任意询问生产相关问题 — 基于实时数据" },
  "Output is +2% vs plan, but Line B changeover is dragging OEE. Ask me to explain a loss, find the bottleneck, or recommend actions.": { th: "ผลผลิต +2% เทียบกับแผน แต่การเปลี่ยนรุ่น Line B กำลังฉุด OEE ถามฉันให้อธิบายการสูญเสีย หาคอขวด หรือแนะนำการดำเนินการได้", ja: "産出は計画比+2%ですが、Line Bの段取り替えがOEEを押し下げています。損失の説明、ボトルネックの特定、対策の提案をお申し付けください。", zh: "产出较计划+2%，但Line B换型正拖累OEE。可让我解释某项损失、找出瓶颈或建议措施。" },
  "Explain today's OEE loss": { th: "อธิบายการสูญเสีย OEE ของวันนี้", ja: "本日のOEE損失を説明", zh: "解释今日的OEE损失" },
  "Explain the biggest downtime event": { th: "อธิบายเหตุการณ์ดาวน์ไทม์ที่ใหญ่ที่สุด", ja: "最大のダウンタイムイベントを説明", zh: "解释最大的停机事件" },
  "Explain the scrap rate": { th: "อธิบายอัตราเศษเสีย", ja: "スクラップ率を説明", zh: "解释废品率" },
  "Where is the bottleneck?": { th: "คอขวดอยู่ที่ไหน?", ja: "ボトルネックはどこ?", zh: "瓶颈在哪里?" },
  "Recommend actions to lift output": { th: "แนะนำการดำเนินการเพื่อเพิ่มผลผลิต", ja: "産出向上の対策を提案", zh: "建议提升产出的措施" },
  "Ask the Production Copilot…": { th: "ถาม Production Copilot…", ja: "Production Copilotに質問…", zh: "向Production Copilot提问…" },
};
